
import type { Property } from './types';

export const properties: Property[] = [
  {
    id: 'p1',
    title: 'Apartament de Lux 4 Camere - Herăstrău, București',
    price: 450000,
    rooms: 4,
    bathrooms: 3,
    squareFootage: 150,
    totalSurface: 170,
    address: 'Șoseaua Nordului 100, București',
    location: 'București, Herăstrău',
    description: 'Un apartament excepțional cu vedere panoramică spre Parcul Herăstrău, situat într-un complex rezidențial exclusivist. Finisajele de cea mai înaltă calitate, spațiile generoase și luminozitatea naturală definesc această proprietate. Apartamentul dispune de un living spectaculos, bucătărie complet utilată, trei dormitoare, trei băi și o terasă generoasă de 20mp.',
    images: [
        { url: 'https://picsum.photos/seed/p1a/1200/800', alt: 'Living room cu vedere panoramică' },
        { url: 'https://picsum.photos/seed/p1b/1200/800', alt: 'Bucătărie modernă, complet utilată' },
        { url: 'https://picsum.photos/seed/p1c/1200/800', alt: 'Dormitor matrimonial spațios' },
        { url: 'https://picsum.photos/seed/p1d/1200/800', alt: 'Baie de lux cu finisaje premium' },
        { url: 'https://picsum.photos/seed/p1e/1200/800', alt: 'Terasă cu vedere spre parc' },
        { url: 'https://picsum.photos/seed/p1f/1200/800', alt: 'Dormitor secundar' },
        { url: 'https://picsum.photos/seed/p1g/1200/800', alt: 'Hol de intrare' },
        { url: 'https://picsum.photos/seed/p1h/1200/800', alt: 'Fațada clădirii' }
    ],
    agent: { name: 'Andrei Popescu', avatarUrl: 'https://i.pravatar.cc/150?u=andrei' },
    latitude: 44.477,
    longitude: 26.082,
    propertyType: 'Apartament',
    transactionType: 'Vânzare',
    constructionYear: 2021,
    floor: '6',
    totalFloors: 7,
    comfort: 'Lux',
    interiorState: 'Nou',
    furnishing: 'Nemobilat',
    heatingSystem: 'Încălzire în pardoseală',
    parking: '2 locuri subteran',
    amenities: ['Pază 24/7', 'Piscină interioară', 'Sală de fitness', 'Saună', 'Recepție', 'Loc de joacă pentru copii', 'Parcare subterană', 'Sistem Smart Home'],
    keyFeatures: 'vedere parc, terasă generoasă, complex exclusivist, finisaje premium, piscină',
    tagline: '4 camere | 3 băi | 150mp',
    status: 'Activ',
    featured: true,
    nearMetro: true,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'p2',
    title: 'Vilă Individuală Modernă - Bună Ziua, Cluj-Napoca',
    price: 890000,
    rooms: 6,
    bathrooms: 4,
    squareFootage: 320,
    totalSurface: 400,
    address: 'Str. Bună Ziua 50, Cluj-Napoca',
    location: 'Cluj-Napoca, Bună Ziua',
    description: 'O proprietate deosebită, cu arhitectură modernă și grădină peisagistică, situată în una dintre cele mai râvnite zone din Cluj-Napoca. Vila oferă spații de locuit ample, o piscină exterioară încălzită și finisaje de cea mai înaltă calitate, fiind ideală pentru o familie care caută confort și intimitate.',
    images: [
        { url: 'https://picsum.photos/seed/p2a/1200/800', alt: 'Fațada vilei moderne' },
        { url: 'https://picsum.photos/seed/p2b/1200/800', alt: 'Living open-space cu șemineu' },
        { url: 'https://picsum.photos/seed/p2c/1200/800', alt: 'Piscină exterioară și grădină' },
        { url: 'https://picsum.photos/seed/p2d/1200/800', alt: 'Bucătărie cu insulă și echipamente profesionale' },
        { url: 'https://picsum.photos/seed/p2e/1200/800', alt: 'Dormitor matrimonial cu dressing' },
        { url: 'https://picsum.photos/seed/p2f/1200/800', alt: 'Terasă acoperită cu zonă de dining' },
        { url: 'https://picsum.photos/seed/p2g/1200/800', alt: 'Baie cu cadă freestanding' },
        { url: 'https://picsum.photos/seed/p2h/1200/800', alt: 'Grădină peisagistică' }
    ],
    agent: { name: 'Elena Ionescu', avatarUrl: 'https://i.pravatar.cc/150?u=elena' },
    latitude: 46.752,
    longitude: 23.585,
    propertyType: 'Casă/Vilă',
    transactionType: 'Vânzare',
    constructionYear: 2022,
    floor: 'P+1E',
    totalFloors: 1,
    comfort: 'Lux',
    interiorState: 'Nou',
    furnishing: 'Parțial',
    heatingSystem: 'Centrală proprie pe gaz',
    parking: 'Garaj dublu',
    amenities: ['Grădină amenajată', 'Piscină exterioară încălzită', 'Garaj dublu', 'Sistem de irigații automat', 'Terasă acoperită', 'Zonă BBQ', 'Șemineu', 'Cramă'],
    keyFeatures: 'piscină, grădină mare, arhitectură modernă, zonă premium, garaj dublu',
    tagline: '6 camere | 4 băi | 320mp',
    status: 'Activ',
    featured: true,
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'p3',
    title: 'Apartament 2 Camere de Închiriat - Complex ISHO, Timișoara',
    price: 700,
    rooms: 2,
    bathrooms: 1,
    squareFootage: 55,
    totalSurface: 65,
    address: 'Bulevardul Take Ionescu 50, Timișoara',
    location: 'Timișoara, ISHO',
    description: 'Apartament nou, la prima închiriere, în cel mai modern complex din Timișoara. Beneficiază de finisaje moderne, este complet mobilat și utilat și dispune de un loc de parcare subteran. Complexul oferă acces la restaurante, cafenele și sală de fitness.',
    images: [
        { url: 'https://picsum.photos/seed/p3a/1200/800', alt: 'Living luminos și modern' },
        { url: 'https://picsum.photos/seed/p3b/1200/800', alt: 'Bucătărie complet utilată' },
        { url: 'https://picsum.photos/seed/p3c/1200/800', alt: 'Dormitor confortabil' },
        { url: 'https://picsum.photos/seed/p3d/1200/800', alt: 'Balcon cu vedere spre oraș' },
        { url: 'https://picsum.photos/seed/p3e/1200/800', alt: 'Baie cu duș walk-in' },
        { url: 'https://picsum.photos/seed/p3f/1200/800', alt: 'Complexul ISHO pe timp de noapte' },
        { url: 'https://picsum.photos/seed/p3g/1200/800', alt: 'Holul de intrare în apartament' },
        { url: 'https://picsum.photos/seed/p3h/1200/800', alt: 'Recepția clădirii' }
    ],
    agent: { name: 'Mihai Ionescu', avatarUrl: 'https://i.pravatar.cc/150?u=mihai' },
    latitude: 45.759,
    longitude: 21.240,
    propertyType: 'Apartament',
    transactionType: 'Închiriere',
    constructionYear: 2023,
    floor: '8',
    totalFloors: 12,
    comfort: '1',
    interiorState: 'Nou',
    furnishing: 'Complet',
    heatingSystem: 'Centrală de imobil',
    parking: 'Subteran',
    amenities: ['Mobilat complet', 'Utilat complet', 'Mașină de spălat vase', 'Aer condiționat', 'Balcon', 'Loc de parcare subteran', 'Acces la sală de fitness', 'Pază'],
    keyFeatures: 'complex nou, mobilat modern, parcare subterană, prima închiriere, central',
    tagline: '2 camere | 1 baie | 55mp',
    status: 'Activ',
    featured: false,
    createdAt: new Date(Date.now() - 31 * 24 * 60 * 60 * 1000).toISOString(),
  },
   {
    id: 'p4',
    title: 'Penthouse Spectaculos cu Vedere la Mare - Mamaia Nord',
    price: 650000,
    rooms: 4,
    bathrooms: 3,
    squareFootage: 180,
    totalSurface: 300,
    address: 'Bulevardul Mamaia Nord 10, Năvodari',
    location: 'Mamaia Nord, Năvodari',
    description: 'Un penthouse unic, cu o terasă imensă de 120mp și vedere frontală la Marea Neagră. Proprietatea este finisată la standarde de lux, cu un design interior semnat de un arhitect renumit și dispune de un jacuzzi pe terasă, fiind locul perfect pentru a vă bucura de răsărit.',
    images: [
        { url: 'https://picsum.photos/seed/p4a/1200/800', alt: 'Terasă imensă cu vedere la mare' },
        { url: 'https://picsum.photos/seed/p4b/1200/800', alt: 'Living cu deschidere spre terasă' },
        { url: 'https://picsum.photos/seed/p4c/1200/800', alt: 'Jacuzzi pe terasă' },
        { url: 'https://picsum.photos/seed/p4d/1200/800', alt: 'Dormitor cu vedere la mare' },
        { url: 'https://picsum.photos/seed/p4e/1200/800', alt: 'Bucătărie de designer' },
        { url: 'https://picsum.photos/seed/p4f/1200/800', alt: 'Baie cu finisaje de lux' },
        { url: 'https://picsum.photos/seed/p4g/1200/800', alt: 'Răsărit de soare de pe terasă' },
        { url: 'https://picsum.photos/seed/p4h/1200/800', alt: 'Clădirea văzută de pe plajă' }
    ],
    agent: { name: 'Andrei Popescu', avatarUrl: 'https://i.pravatar.cc/150?u=andrei' },
    latitude: 44.275,
    longitude: 28.630,
    propertyType: 'Apartament',
    transactionType: 'Vânzare',
    constructionYear: 2020,
    floor: '9',
    totalFloors: 9,
    comfort: 'Lux',
    interiorState: 'Renovat',
    furnishing: 'Complet',
    heatingSystem: 'Centrală proprie pe gaz',
    parking: '2 locuri subteran',
    amenities: ['Terasă panoramică', 'Jacuzzi pe terasă', 'Vedere la mare', 'Mobilat de designer', 'Bucătărie de vară', 'Sistem audio integrat', 'Parcare subterană', 'Acces direct la plajă'],
    keyFeatures: 'vedere frontală la mare, terasă 120mp, jacuzzi, design de lux, acces plajă',
    tagline: '4 camere | 3 băi | 180mp',
    status: 'Activ',
    featured: true,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'p5',
    title: 'Casă Tradițională Superb Renovată - Centrul Istoric, Brașov',
    price: 550000,
    rooms: 5,
    bathrooms: 3,
    squareFootage: 200,
    totalSurface: 250,
    address: 'Strada Michael Weiss 15, Brașov',
    location: 'Brașov, Centrul Istoric',
    description: 'Proprietate cu farmec istoric, complet renovată, păstrând elementele originale, precum grinzile de lemn și tâmplăria. Dispune de o curte interioară intimă și o cramă la subsol, fiind perfectă pentru cei ce apreciază autenticitatea și confortul modern.',
    images: [
        { url: 'https://picsum.photos/seed/p5a/1200/800', alt: 'Fațada casei istorice' },
        { url: 'https://picsum.photos/seed/p5b/1200/800', alt: 'Living cu șemineu și grinzi de lemn' },
        { url: 'https://picsum.photos/seed/p5c/1200/800', alt: 'Curte interioară pavată' },
        { url: 'https://picsum.photos/seed/p5d/1200/800', alt: 'Bucătărie modernă în stil rustic' },
        { url: 'https://picsum.photos/seed/p5e/1200/800', alt: 'Dormitor la mansardă' },
        { url: 'https://picsum.photos/seed/p5f/1200/800', alt: 'Cramă de vinuri la subsol' },
        { url: 'https://picsum.photos/seed/p5g/1200/800', alt: 'Baie cu detalii din piatră' },
        { url: 'https://picsum.photos/seed/p5h/1200/800', alt: 'Detaliu arhitectural' }
    ],
    agent: { name: 'Elena Ionescu', avatarUrl: 'https://i.pravatar.cc/150?u=elena' },
    latitude: 45.642,
    longitude: 25.589,
    propertyType: 'Casă/Vilă',
    transactionType: 'Vânzare',
    constructionYear: 1920,
    floor: 'P+E',
    totalFloors: 1,
    comfort: '1',
    interiorState: 'Renovat',
    furnishing: 'Complet',
    heatingSystem: 'Centrală proprie pe gaz',
    parking: 'Fără',
    amenities: ['Curte interioară', 'Cramă', 'Mobilier din lemn masiv', 'Șemineu funcțional', 'Grinzi de lemn aparente', 'Bucătărie modernă', 'Izolație termică', 'Centrală termică'],
    keyFeatures: 'centru istoric, curte interioară, renovat cu gust, elemente originale, cramă',
    tagline: '5 camere | 3 băi | 200mp',
    status: 'Activ',
    featured: false,
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'p6',
    title: 'Apartament 3 Camere Decomandat - Copou, Iași',
    price: 165000,
    rooms: 3,
    bathrooms: 2,
    squareFootage: 78,
    totalSurface: 85,
    address: 'Aleea Grigore Ghica Vodă 20, Iași',
    location: 'Iași, Copou',
    description: 'Apartament spațios și luminos, situat în cea mai verde și liniștită zonă din Iași, Copou. Proprietatea este decomandată, dispune de două băi și două balcoane, și se află la câțiva pași de Parcul Copou și universități. Ideal pentru o familie sau ca investiție.',
    images: [
        { url: 'https://picsum.photos/seed/p6a/1200/800', alt: 'Living spațios' },
        { url: 'https://picsum.photos/seed/p6b/1200/800', alt: 'Dormitor cu ieșire pe balcon' },
        { url: 'https://picsum.photos/seed/p6c/1200/800', alt: 'Al doilea dormitor' },
        { url: 'https://picsum.photos/seed/p6d/1200/800', alt: 'Bucătărie' },
        { url: 'https://picsum.photos/seed/p6e/1200/800', alt: 'Baie principală' },
        { url: 'https://picsum.photos/seed/p6f/1200/800', alt: 'Baie de serviciu' },
        { url: 'https://picsum.photos/seed/p6g/1200/800', alt: 'Vedere de pe balcon' },
        { url: 'https://picsum.photos/seed/p6h/1200/800', alt: 'Blocul' }
    ],
    agent: { name: 'Mihai Ionescu', avatarUrl: 'https://i.pravatar.cc/150?u=mihai' },
    latitude: 47.177,
    longitude: 27.570,
    propertyType: 'Apartament',
    transactionType: 'Vânzare',
    constructionYear: 1988,
    floor: '3',
    totalFloors: 8,
    comfort: '1',
    interiorState: 'Bună',
    furnishing: 'Parțial',
    heatingSystem: 'Termoficare',
    parking: 'Loc exterior',
    amenities: ['Parc în apropiere', 'Două balcoane', 'Boxă la subsol', 'Loc de parcare', 'Izolat termic', 'Aer condiționat', 'Vedere pe două părți', 'Mobilat'],
    keyFeatures: 'zonă Copou, decomandat, spațios, două băi, parc aproape, etaj 3',
    tagline: '3 camere | 2 băi | 78mp',
    status: 'Activ',
    featured: false,
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'p7',
    title: 'Teren Intravilan cu Deschidere la Lac - Snagov',
    price: 350000,
    rooms: 0,
    bathrooms: 0,
    squareFootage: 1200,
    totalSurface: 1200,
    address: 'Strada Lacului 1, Snagov',
    location: 'Snagov, Ilfov',
    description: 'Teren intravilan excepțional, cu o suprafață de 1200mp și deschidere directă la Lacul Snagov de 25m. Terenul este plat, are toate utilitățile la stradă (gaz, curent, apă, canalizare) și dispune de un ponton propriu. Este ideal pentru construcția unei vile de vis.',
    images: [
        { url: 'https://picsum.photos/seed/p7a/1200/800', alt: 'Teren cu deschidere la lac' },
        { url: 'https://picsum.photos/seed/p7b/1200/800', alt: 'Ponton privat' },
        { url: 'https://picsum.photos/seed/p7c/1200/800', alt: 'Vedere spre lac' },
        { url: 'https://picsum.photos/seed/p7d/1200/800', alt: 'Apus de soare pe lac' },
        { url: 'https://picsum.photos/seed/p7e/1200/800', alt: 'Pădurea din apropiere' },
        { url: 'https://picsum.photos/seed/p7f/1200/800', alt: 'Delimitarea terenului' },
        { url: 'https://picsum.photos/seed/p7g/1200/800', alt: 'Drum de acces' },
        { url: 'https://picsum.photos/seed/p7h/1200/800', alt: 'Imagine aeriană a zonei' }
    ],
    agent: { name: 'Andrei Popescu', avatarUrl: 'https://i.pravatar.cc/150?u=andrei' },
    latitude: 44.710,
    longitude: 26.170,
    propertyType: 'Teren',
    transactionType: 'Vânzare',
    constructionYear: undefined,
    floor: undefined,
    totalFloors: undefined,
    comfort: undefined,
    interiorState: undefined,
    furnishing: undefined,
    heatingSystem: undefined,
    parking: undefined,
    amenities: ['Deschidere la lac', 'Ponton', 'Utilități la stradă', 'Gard', 'Zonă pădure', 'Drum asfaltat', 'Vecinătăți premium', 'PUZ aprobat'],
    keyFeatures: 'deschidere la lac, ponton, zonă exclusivistă, utilități, 1200mp',
    tagline: '1200mp | Deschidere lac',
    status: 'Activ',
    featured: false,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'p8',
    title: 'Spațiu Comercial Stradal de Închiriat - Calea Victoriei, București',
    price: 5000,
    rooms: 1,
    bathrooms: 2,
    squareFootage: 150,
    totalSurface: 160,
    address: 'Calea Victoriei 100, București',
    location: 'București, Calea Victoriei',
    description: 'Spațiu comercial cu vitrină generoasă de 10 metri, situat pe Calea Victoriei, cu trafic pietonal intens. Spațiul este open-space, pretabil pentru magazin de prezentare, boutique de lux, cafenea sau galerie de artă. Dispune de vizibilitate excepțională.',
    images: [
        { url: 'https://picsum.photos/seed/p8a/1200/800', alt: 'Vitrină spațiu comercial' },
        { url: 'https://picsum.photos/seed/p8b/1200/800', alt: 'Interior open-space' },
        { url: 'https://picsum.photos/seed/p8c/1200/800', alt: 'Trafic pietonal în fața spațiului' },
        { url: 'https://picsum.photos/seed/p8d/1200/800', alt: 'Intrarea în spațiu' },
        { url: 'https://picsum.photos/seed/p8e/1200/800', alt: 'Vedere din interior spre stradă' },
        { url: 'https://picsum.photos/seed/p8f/1200/800', alt: 'Grup sanitar' },
        { url: 'https://picsum.photos/seed/p8g/1200/800', alt: 'Calea Victoriei' },
        { url: 'https://picsum.photos/seed/p8h/1200/800', alt: 'Schița spațiului' }
    ],
    agent: { name: 'Elena Ionescu', avatarUrl: 'https://i.pravatar.cc/150?u=elena' },
    latitude: 44.437,
    longitude: 26.096,
    propertyType: 'Spațiu Comercial',
    transactionType: 'Închiriere',
    constructionYear: 1950,
    floor: 'Parter',
    totalFloors: 6,
    comfort: undefined,
    interiorState: 'Renovat',
    furnishing: 'Nemobilat',
    heatingSystem: 'Centrală proprie',
    parking: 'Fără',
    amenities: ['Vitrină mare', 'Trafic pietonal', 'Open space', 'Grupuri sanitare', 'Sistem de climatizare', 'Sistem de alarmă', 'Vizibilitate excelentă', 'Spațiu de depozitare'],
    keyFeatures: 'ultracentral, Calea Victoriei, vitrină mare, trafic intens, vizibilitate',
    tagline: '150mp | Stradal',
    status: 'Activ',
    featured: true,
    nearMetro: true,
    createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'p9',
    title: 'Garsonieră Smart de Închiriat - Mărăști, Cluj-Napoca',
    price: 400,
    rooms: 1,
    bathrooms: 1,
    squareFootage: 32,
    totalSurface: 35,
    address: 'Aleea Bibliotecii 10, Cluj-Napoca',
    location: 'Cluj-Napoca, Mărăști',
    description: 'Garsonieră complet utilată și mobilată modern, ideală pentru studenți sau tineri profesioniști. Situată într-un imobil nou, aproape de FSEGA și Iulius Mall, dispune de costuri de întreținere reduse și un balcon cochet.',
    images: [
        { url: 'https://picsum.photos/seed/p9a/1200/800', alt: 'Open space' },
        { url: 'https://picsum.photos/seed/p9b/1200/800', alt: 'Chicinetă utilată' },
        { url: 'https://picsum.photos/seed/p9c/1200/800', alt: 'Zonă de dormit' },
        { url: 'https://picsum.photos/seed/p9d/1200/800', alt: 'Baie modernă' },
        { url: 'https://picsum.photos/seed/p9e/1200/800', alt: 'Balcon' },
        { url: 'https://picsum.photos/seed/p9f/1200/800', alt: 'Birou de lucru' },
        { url: 'https://picsum.photos/seed/p9g/1200/800', alt: 'Dressing' },
        { url: 'https://picsum.photos/seed/p9h/1200/800', alt: 'Vedere de pe balcon' }
    ],
    agent: { name: 'Mihai Ionescu', avatarUrl: 'https://i.pravatar.cc/150?u=mihai' },
    latitude: 46.778,
    longitude: 23.612,
    propertyType: 'Garsonieră',
    transactionType: 'Închiriere',
    constructionYear: 2019,
    floor: '4',
    totalFloors: 10,
    comfort: '1',
    interiorState: 'Nou',
    furnishing: 'Complet',
    heatingSystem: 'Centrală de imobil',
    parking: 'Fără',
    amenities: ['Mobilier IKEA', 'Smart TV', 'Mașină de spălat haine', 'Cuptor cu microunde', 'Aer condiționat', 'Balcon', 'Costuri reduse', 'Aproape de transport în comun'],
    keyFeatures: 'aproape Iulius Mall, mobilat modern, etaj intermediar, costuri mici, bloc nou',
    tagline: 'Studio | 1 baie | 32mp',
    status: 'Activ',
    featured: false,
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'p10',
    title: 'Casă Bătrânească cu Teren Mare - Corbeanca',
    price: 120000,
    rooms: 2,
    bathrooms: 1,
    squareFootage: 80,
    totalSurface: 1500,
    address: 'Strada Principală 150, Corbeanca, Ilfov',
    location: 'Corbeanca, Ilfov',
    description: 'Oportunitate de investiție: casă bătrânească demolabilă/renovabilă pe un teren generos de 1500mp, cu deschidere de 20m. Proprietatea se află într-o zonă liniștită, în plină dezvoltare, având toate utilitățile la poartă (gaz, curent, apă, canalizare).',
    images: [
        { url: 'https://picsum.photos/seed/p10a/1200/800', alt: 'Vedere de ansamblu a proprietății' },
        { url: 'https://picsum.photos/seed/p10b/1200/800', alt: 'Terenul generos' },
        { url: 'https://picsum.photos/seed/p10c/1200/800', alt: 'Casa bătrânească' },
        { url: 'https://picsum.photos/seed/p10d/1200/800', alt: 'Deschiderea la stradă' },
        { url: 'https://picsum.photos/seed/p10e/1200/800', alt: 'Livada din spatele curții' },
        { url: 'https://picsum.photos/seed/p10f/1200/800', alt: 'Zonă învecinată' },
        { url: 'https://picsum.photos/seed/p10g/1200/800', alt: 'Plan cadastral' },
        { url: 'https://picsum.photos/seed/p10h/1200/800', alt: 'Utilități la poartă' }
    ],
    agent: { name: 'Andrei Popescu', avatarUrl: 'https://i.pravatar.cc/150?u=andrei' },
    latitude: 44.595,
    longitude: 26.040,
    propertyType: 'Casă/Vilă',
    transactionType: 'Vânzare',
    constructionYear: 1960,
    floor: 'Parter',
    totalFloors: 0,
    comfort: '3',
    interiorState: 'Necesită renovare',
    furnishing: 'Nemobilat',
    heatingSystem: 'Sobă/Șemineu',
    parking: 'În curte',
    amenities: ['Teren 1500mp', 'Deschidere 20m', 'Gaze la poartă', 'Curent electric la poartă', 'Apă curentă la poartă', 'Canalizare la poartă', 'Zonă liniștită', 'Potențial de construcție vilă'],
    keyFeatures: 'teren mare 1500mp, utilități, oportunitate investiție, zonă în dezvoltare',
    tagline: 'Teren 1500mp | Oportunitate',
    status: 'Activ',
    featured: false,
    createdAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
