
import type { Property } from './types';

export const properties: Property[] = [
  {
    id: 'p1',
    title: 'Apartament modern cu 3 camere, zona de nord',
    price: 185000,
    bedrooms: 3,
    bathrooms: 2,
    squareFootage: 85,
    totalSurface: 95,
    address: 'Str. Primăverii nr. 10, București',
    location: 'București, Primăverii',
    description: 'Un apartament superb, complet renovat, situat într-una dintre cele mai dorite zone din București. Finisajele de lux, spațiul generos și luminozitatea fac din această proprietate alegerea ideală. Dispune de un living spațios, două dormitoare, două băi și un balcon cu o priveliște deosebită. Se vinde complet mobilat și utilat.',
    images: [
        { url: 'https://picsum.photos/seed/p1a/1200/800', alt: 'Living room with city view' },
        { url: 'https://picsum.photos/seed/p1b/1200/800', alt: 'Modern kitchen' },
        { url: 'https://picsum.photos/seed/p1c/1200/800', alt: 'Bedroom with large window' },
        { url: 'https://picsum.photos/seed/p1d/1200/800', alt: 'Rooftop terrace' },
        { url: 'https://picsum.photos/seed/p1e/1200/800', alt: 'Spa-like bathroom' }
    ],
    agent: { name: 'Andrei Popescu', avatarUrl: 'https://i.pravatar.cc/150?u=andrei' },
    latitude: 44.457,
    longitude: 26.085,
    propertyType: 'Apartament',
    transactionType: 'Vânzare',
    constructionYear: 2018,
    floor: '5',
    totalFloors: 8,
    comfort: 'Lux',
    interiorState: 'Renovat',
    furnishing: 'Complet',
    heatingSystem: 'Centrală proprie',
    parking: 'Subteran',
    amenities: ['Aer condiționat', 'Lift', 'Interfon', 'Sistem de alarmă', 'Balcon', 'Terasă'],
    keyFeatures: 'finisaje de lux, vedere panoramică, parcare subterană',
    tagline: '3 dorm. | 2 băi | 85mp',
    imageUrl: 'https://picsum.photos/seed/p1a/800/600',
    imageHint: 'modern apartment',
  },
  {
    id: 'p2',
    title: 'Vilă spațioasă cu grădină, Pipera',
    price: 450000,
    bedrooms: 5,
    bathrooms: 4,
    squareFootage: 220,
    address: 'Aleea Privighetorilor nr. 5, Voluntari',
    location: 'Pipera, Voluntari',
    description: 'Vilă de excepție, perfectă pentru o familie, situată în zona liniștită din Pipera. Proprietatea dispune de o grădină superb amenajată, piscină și spații generoase. Interiorul este modern, cu finisaje de înaltă calitate, și oferă tot confortul necesar unui stil de viață exclusivist.',
    images: [
        { url: 'https://picsum.photos/seed/p2a/1200/800', alt: 'Exterior of suburban home' },
        { url: 'https://picsum.photos/seed/p2b/1200/800', alt: 'Cozy living room with fireplace' },
        { url: 'https://picsum.photos/seed/p2c/1200/800', alt: 'Renovated kitchen' },
        { url: 'https://picsum.photos/seed/p2d/1200/800', alt: 'Large backyard with deck' },
        { url: 'https://picsum.photos/seed/p2e/1200/800', alt: 'Master bedroom' }
    ],
    agent: { name: 'Elena Ionescu', avatarUrl: 'https://i.pravatar.cc/150?u=elena' },
    latitude: 44.512,
    longitude: 26.130,
    propertyType: 'Casă/Vilă',
    transactionType: 'Vânzare',
    constructionYear: 2020,
    floor: 'P+1E+M',
    amenities: ['Grădină', 'Piscină', 'Garaj', 'Sistem de securitate'],
    keyFeatures: 'grădină mare, piscină, zonă liniștită',
    tagline: '5 dorm. | 4 băi | 220mp',
    imageUrl: 'https://picsum.photos/seed/p2a/800/600',
    imageHint: 'luxury villa',
  },
];
