export const locations = {
  'Bucuresti-Ilfov': [
    '13 Septembrie',
    '1 Decembrie',
    '1 Mai',
    'Andronache',
    'Apărătorii Patriei',
    'Arenele Romane',
    'Armeneasca',
    'Aviatorilor',
    'Aviatiei',
    'Baicului',
    'Baneasa',
    'Barbu Vacarescu',
    'Basarab',
    'Basarabia',
    'Bellu',
    'Berceni',
    'Brancoveanu',
    'Bucurestii Noi',
    'Carol',
    'Cartierul Francez',
    'Centrul Civic',
    'Centrul Istoric',
    'Chibrit',
    'Cismigiu',
    'Colentina',
    'Cotroceni',
    'Crangasi',
    'Damaroaia',
    'Dealul Spirii',
    'Diham',
    'Domenii',
    'Dorobanti',
    'Doamna Ghica',
    'Dristor',
    'Drumul Sarii',
    'Drumul Taberei',
    'Dudesti',
    'Eminescu',
    'Ferdinand',
    'Ferentari',
    'Floreasca',
    'Fundeni',
    'Gara de Nord',
    'Ghencea',
    'Giulesti',
    'Giurgiului',
    'Gorjului',
    'Grivita',
    'Grand Arena',
    'Herastrau',
    'Iancu Nicolae',
    'Iancului',
    'Ion Mihalache',
    'Izvor',
    'Jiului',
    'Lacul Morii',
    'Lacul Tei',
    'Libertatii',
    'Luica',
    'Militari',
    'Mihai Bravu',
    'Mihalache',
    'Mosilor',
    'Obor',
    'Oltenitei',
    'Pache Protopopescu',
    'Pajura',
    'Panduri',
    'Pantelimon (sector)',
    'Parcul Carol',
    'Parcul Circului',
    'Parcul Tineretului',
    'Piata Alba Iulia',
    'Piata Chibrit',
    'Piata Domenii',
    'Piata Iancului',
    'Piata Muncii',
    'Piata Presei',
    'Piata Romana',
    'Piata Sudului',
    'Piata Unirii',
    'Piata Victoriei',
    'Pipera',
    'Plevnei',
    'Politehnica',
    'Popesti',
    'Primaverii',
    'Progresul',
    'Rahova',
    'Regie',
    'Romana',
    'Rosetti',
    'Salajan',
    'Sebastian',
    'Sisesti',
    'Splaiul Independentei',
    'Stefan cel Mare',
    'Straulesti',
    'Tei',
    'Theodor Pallady',
    'Timpuri Noi',
    'Tineretului',
    'Titan',
    'Unirii',
    'Universitate',
    'Vatra Luminoasa',
    'Vacaresti',
    'Vitan',
    'Vitan-Barzesti',
    'Afumati',
    'Balotesti',
    'Bragadiru',
    'Buftea',
    'Cernica',
    'Chiajna',
    'Chitila',
    'Ciorogarla',
    'Clinceni',
    'Corbeanca',
    'Cornetu',
    'Darasti',
    'Dascalu',
    'Dobroesti',
    'Domnesti',
    'Dragomiresti-Vale',
    'Glina',
    'Gradistea',
    'Gruiu',
    'Jilava',
    'Magurele',
    'Moara Vlasiei',
    'Mogosoaia',
    'Nuci',
    'Otopeni',
    'Pantelimon (oras)',
    'Petrachioaia',
    'Popesti-Leordeni',
    'Snagov',
    'Stefanestii de Jos',
    'Tunari',
    'Vidra',
    'Voluntari',
  ],
  'Cluj-Napoca': [
    'Andrei Muresanu',
    'Borhanci',
    'Buna Ziua',
    'Campului',
    'Centru',
    'Dambul Rotund',
    'Europa',
    'Faget',
    'Gheorgheni',
    'Grigorescu',
    'Gruia',
    'Iris',
    'Intre Lacuri',
    'Manastur',
    'Marasti',
    'Plopilor',
    'Semicentral',
    'Someseni',
    'Sopor',
    'Zorilor',
    'Apahida',
    'Baciu',
    'Chinteni',
    'Dezmir',
    'Feleacu',
    'Floresti',
    'Gilau',
    'Jucu',
  ],
  'Timisoara': [
    'Aradului',
    'Badea Cartan',
    'Blascovici',
    'Braytim',
    'Bucovina',
    'Calea Aradului',
    'Calea Girocului',
    'Calea Lipovei',
    'Calea Lugojului',
    'Calea Martirilor',
    'Calea Sagului',
    'Cetate',
    'Complex Studentesc',
    'Dacia',
    'Elisabetin',
    'Fabric',
    'Freidorf',
    'Fratelia',
    'Iosefin',
    'Kuncz',
    'Lipovei',
    'Mehala',
    'Modern',
    'Olimpia-Stadion',
    'Plopi',
    'Ronat',
    'Soarelui',
    'Take Ionescu',
    'Tipografilor',
    'Torontalului',
    'Circumvalatiunii',
    'Dumbravita',
    'Ghiroda',
    'Giroc',
    'Mosnita Noua',
    'Sacalaz',
    'Sanmihaiu Roman',
    'Urseni',
  ],
  'Iasi': [
    'Alexandru cel Bun',
    'Aviatiei',
    'Baza 3',
    'Bucium',
    'Bularga',
    'Canta',
    'Centru',
    'Centru Civic',
    'Copou',
    'CUG',
    'Dacia',
    'Galata',
    'Gara',
    'Moara de Vant',
    'Metalurgie',
    'Mircea cel Batran',
    'Nicolina',
    'Pacurari',
    'Podu Ros',
    'Sararie',
    'Soseaua Nationala',
    'Tatarasi',
    'Tudor Vladimirescu',
    'Valea Adanca',
    'Valea Lupului',
    'Zimbru',
    'Zorilor',
    'Barnova',
    'Ciurea',
    'Holboca',
    'Miroslava',
    'Rediu',
    'Tomesti',
  ],
  'Constanta': [
    'Abator',
    'Badea Cartan',
    'Brick',
    'Brotacei',
    'Casa de Cultura',
    'Centru',
    'Coiciu',
    'Dacia',
    'Energia',
    'Faleza Nord',
    'Faleza Sud',
    'Far',
    'Gara',
    'Halta Traian',
    'ICIL',
    'Inel I',
    'Inel II',
    'Km 4',
    'Km 5',
    'Mamaia',
    'Mamaia Nord',
    'Palas',
    'Peninsula',
    'Poarta 6',
    'Port',
    'Tomis I',
    'Tomis II',
    'Tomis III',
    'Tomis Nord',
    'Agigea',
    'Cumpana',
    'Eforie Nord',
    'Eforie Sud',
    'Lazu',
    'Lumina',
    'Navodari',
    'Ovidiu',
    'Valu lui Traian',
  ],
  Brasov: [
    'Astra',
    'Bartolomeu',
    'Blumana',
    'Calea Bucuresti',
    'Centrul Civic',
    'Centrul Istoric',
    'Craiter',
    'Florilor',
    'Garii',
    'Noua',
    'Racadau',
    'Schei',
    'Scriitorilor',
    'Stupini',
    'Tractorul',
    'Avantgarden',
    'Sanpetru',
    'Sacele',
  ],
  Sibiu: [
    'Cedonia',
    'Central',
    'Hipodrom 1',
    'Hipodrom 2',
    'Hipodrom 3',
    'Lazaret',
    'Mihai Viteazu',
    'Piata Cluj',
    'Rahovei',
    'Selimbar',
    'Strand',
    'Turnisor',
    'Valea Aurie',
    'Vasile Aaron',
  ],
} as const;

export type City = keyof typeof locations;
