Foreground true
User clamav
TCPSocket 3310
TCPAddr 127.0.0.1
PidFile /tmp/clamd.pid
DatabaseDirectory /var/lib/clamav
OfficialDatabaseOnly true
SelfCheck 600
ConcurrentDatabaseReload true
MaxThreads 1
MaxQueue 4
MaxConnectionQueueLength 8
ReadTimeout 120
CommandReadTimeout 30
SendBufTimeout 120
StreamMaxLength 20M
MaxFileSize 20M
MaxScanSize 80M
MaxRecursion 16
MaxFiles 10000
AlertExceedsMax true
ScanArchive true
ScanPDF true
ScanOLE2 true
ScanMail true
Bytecode true
LogTime true
LogClean false
