import { z } from 'zod';
import { propertyExtraFields, canonicalLocationSchema, propertyLifecycleSchema } from '@/lib/crm/action-fields';
import { profilePatchSchema, agencyPatchSchema, notificationPreferencesPatchSchema } from '@/lib/crm/settings-fields';
const taskDetails = { participantName: z.string().max(180).nullable().optional(), participantPhone: z.string().max(60).nullable().optional(), startTime: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/).optional(), duration: z.number().int().min(1).max(1440).optional() };
const canonicalLocation = canonicalLocationSchema;
const buyerLocation = z.object({ preference: z.enum(['preferred', 'acceptable', 'excluded']), scope: z.enum(['location', 'locality']), location: canonicalLocation.nullable().optional(), locality: z.string().max(200).nullable().optional(), source: z.enum(['manual', 'legacy_zone', 'legacy_city', 'legacy_general_zone', 'legacy_text', 'migration']).optional(), sourceText: z.string().max(1000).nullable().optional(), weight: z.number().min(0).max(100).optional() }).strict();

export const idSchema = z.string().min(1).max(180).regex(/^[^/]+$/);
export const resourceNames = ['contacts', 'properties', 'tasks', 'viewings', 'ownerListingFavorites', 'sales', 'contractTemplates', 'generatedContracts', 'conversations', 'channelConnections', 'socialPosts', 'assistantAutomations', 'pricingAnalysisSnapshots', 'pricingAnalysisBacktests', 'propertyStatusEvents', 'propertyDeletionEvents', 'metaCampaignDrafts', 'salesEmailTemplates', 'salesSettings', 'salesTemplateAudit', 'agency', 'agents', 'notifications', 'portals', 'aiOutreachCalls', 'storiaInboxLeads', 'tiktokPostDrafts', 'tiktokStudioAssets', 'tiktokStudioProjects', 'communicationConsents', 'crmEvents', 'assistantUploads', 'profile', 'notificationPreferences'] as const;
export const readSchema = z.object({ resource: z.enum(resourceNames), id: idSchema.optional(), search: z.string().max(300).optional(), cursor: idSchema.optional(), limit: z.number().int().min(1).max(100).default(30) }).strict();
export const queryRecordsSchema = z.object({ resource: z.enum(['contacts', 'properties', 'viewings', 'tasks']), dayOffset: z.number().int().min(-3650).max(3650).optional(), date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(), dateFrom: z.string().datetime({ offset: true }).optional(), dateTo: z.string().datetime({ offset: true }).optional(), status: z.string().max(60).optional(), agentId: idSchema.optional(), contactId: idSchema.optional(), propertyId: idSchema.optional(), search: z.string().max(200).optional(), mode: z.enum(['list', 'count']).default('list'), limit: z.number().int().min(1).max(30).default(8), cursor: idSchema.optional() }).strict();
export const relatedSchema = z.object({ resource: z.enum(['sales', 'conversations', 'aiOutreachCalls', 'portals', 'assistantAutomations']), id: idSchema, collection: z.enum(['documents', 'messages', 'emailMessages', 'audit', 'notes', 'recommendations']), cursor: idSchema.optional(), limit: z.number().int().min(1).max(100).default(30) }).strict();
export type AssistantRelated = z.infer<typeof relatedSchema>;
export const fieldSchema = z.object({ resource: z.enum(resourceNames), id: idSchema, collection: z.enum(['documents', 'messages', 'emailMessages', 'audit', 'notes', 'recommendations']).optional(), documentId: idSchema.optional(), versionId: idSchema.optional(), field: z.array(z.string().min(1).max(120).regex(/^[A-Za-z0-9_-]+$/)).min(1).max(8), offset: z.number().int().nonnegative().default(0), limit: z.number().int().min(1).max(12000).default(100) }).strict();
export function cardPreview(value: unknown, depth = 0): any {
  if (typeof value === 'string') return value.length > 2000 ? value.slice(0, 2000) + '… [previzualizare]' : value;
  if (!value || typeof value !== 'object') return value ?? null;
  if (depth > 4) return '[folosește read_field pentru detalii]';
  if (Array.isArray(value)) return value.slice(0, 5).map(v => cardPreview(v, depth + 1));
  const entries = Object.entries(value).slice(0, 40);
  return { ...Object.fromEntries(entries.map(([key, v]) => [key, cardPreview(v, depth + 1)])), ...('id' in value ? { id: (value as { id: unknown }).id } : {}) };
}
export const searchSchema = z.object({ source: z.enum(['owners', 'crm']).default('owners'), scopeKey: idSchema.optional(), zone: z.string().trim().max(100).optional(), propertyType: z.enum(['apartment', 'house', 'land', 'commercial']).optional(), transactionType: z.enum(['sale', 'rent']).default('sale'), rooms: z.number().int().min(1).max(30).optional(), priceMin: z.number().nonnegative().optional(), priceMax: z.number().positive().optional(), limit: z.number().int().min(1).max(100).default(5), cursor: idSchema.optional() }).strict();
const date = z.string().datetime({ offset: true }).transform(value => new Date(value).toISOString());
const taskDate = z.union([date, z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(value => Number.isFinite(Date.parse(value)) && new Date(value).toISOString().slice(0, 10) === value, 'Data nu este validă.')]);
const timing = { nextRunAt: date, intervalMinutes: z.number().int().min(30).max(43200).optional(), maxRuns: z.number().int().min(1).max(365).default(1), stopAfter: date.optional(), stopOnContactStatuses: z.array(z.enum(['Nou', 'Contactat', 'Vizionare', 'În negociere', 'Câștigat', 'Pierdut'])).max(6).optional() };
export const automationSchema = z.discriminatedUnion('type', [
  z.object({ type: z.literal('followup_task'), ...timing, contactId: idSchema, description: z.string().trim().min(1).max(2000) }).strict(),
  z.object({ type: z.literal('owner_watch'), ...timing, search: searchSchema }).strict(),
  z.object({ type: z.literal('insight_report'), ...timing, limit: z.number().int().min(1).max(30).default(10) }).strict(),
  z.object({ type: z.literal('matching_watch'), ...timing, contactId: idSchema, threshold: z.number().min(0).max(100).default(60), limit: z.number().int().min(1).max(30).default(10) }).strict(),
  z.object({ type: z.literal('whatsapp_template'), ...timing, conversationId: idSchema, stopOnReply: z.boolean().default(true), template: z.object({ name: z.string().min(1).max(200), language: z.string().min(2).max(20), parameters: z.array(z.string().max(1000)).max(20).default([]) }).strict() }).strict(),
]);
const contactPatch = z.object({ contactType: z.enum(['Cumparator', 'Client', 'Partener']).optional(), financialStatus: z.enum(['Neprecalificat', 'Credit Pre-aprobat', 'Credit Aprobat', 'Cash']).optional(), leadScore: z.number().min(0).max(100).optional(), leadScoreReason: z.string().max(10000).optional(), locationPreferencesV2: z.array(buyerLocation).max(100).nullable().optional(), generalZone: z.enum(['Nord', 'Sud', 'Est', 'Vest', 'Central', 'Oricare', 'all']).nullable().optional(), address: z.string().max(500).optional(), personalNumericCode: z.string().max(30).optional(), identityDocumentSeries: z.string().max(30).optional(), identityDocumentNumber: z.string().max(50).optional(), entityType: z.enum(['individual', 'company']).optional(), legalCompanyName: z.string().max(300).optional(), companyTaxId: z.string().max(80).optional(), tradeRegisterNumber: z.string().max(100).optional(), registeredOffice: z.string().max(500).optional(), legalRepresentative: z.string().max(200).optional(), photoUrl: z.string().url().optional(), name: z.string().trim().min(1).max(200).optional(), phone: z.string().max(40).optional(), email: z.string().email().or(z.literal('')).optional(), status: z.enum(['Nou', 'Contactat', 'Vizionare', 'În negociere', 'Câștigat', 'Pierdut']).optional(), priority: z.enum(['Scăzută', 'Medie', 'Ridicată']).optional(), tags: z.array(z.string().max(80)).max(30).optional(), budget: z.number().nonnegative().optional(), city: z.string().max(100).optional(), zones: z.array(z.string().max(100)).max(30).optional(), description: z.string().max(10000).optional(), source: z.string().max(200).optional(), sourcePropertyId: idSchema.nullable().optional() }).strict();
const preferences = z.object({ desiredPriceRangeMin: z.number().nonnegative().optional(), desiredPriceRangeMax: z.number().nonnegative().optional(), desiredRooms: z.number().int().nonnegative().max(30).optional(), desiredBathrooms: z.number().int().nonnegative().max(30).optional(), desiredSquareFootageMin: z.number().nonnegative().optional(), desiredSquareFootageMax: z.number().nonnegative().optional(), desiredFeatures: z.string().max(4000).optional(), locationPreferences: z.string().max(4000).optional() }).strict();
export const propertyPatch = z.object({ ...propertyExtraFields, title: z.string().trim().min(1).max(300).optional(), address: z.string().trim().min(1).max(500).optional(), images: z.array(z.object({ url: z.string().url(), alt: z.string().max(500) }).strict()).max(40).optional(), description: z.string().max(20000).optional(), price: z.number().positive().max(1e9).optional(), notes: z.string().max(10000).optional(), featured: z.boolean().optional(), rooms: z.number().int().nonnegative().max(100).optional(), bathrooms: z.number().int().nonnegative().max(100).optional(), squareFootage: z.number().positive().max(1e7).optional() }).strict();
export const actionSchema = z.discriminatedUnion('kind', [
  z.object({ kind: z.literal('update_profile'), patch: profilePatchSchema }).strict(),
  z.object({ kind: z.literal('update_agency'), patch: agencyPatchSchema }).strict(),
  z.object({ kind: z.literal('update_notification_preferences'), patch: notificationPreferencesPatchSchema }).strict(),
  z.object({ kind: z.literal('storia_lead_action'), leadId: idSchema, action: z.enum(['update', 'convert']), patch: z.object({ status: z.enum(['nou', 'in_lucru', 'raspuns', 'inchis']).optional(), unread: z.boolean().optional() }).strict().optional() }).strict(),
  z.object({ kind: z.literal('preferences_link_action'), contactId: idSchema, action: z.enum(['create', 'regenerate', 'deactivate']) }).strict(),
  z.object({ kind: z.literal('update_recommendation'), contactId: idSchema, propertyId: idSchema, patch: z.object({ clientFeedback: z.enum(['liked', 'disliked', 'none']).optional(), clientComment: z.string().max(3000).optional() }).strict().refine(value => Object.keys(value).length > 0) }).strict(),
  z.object({ kind: z.literal('contract_template_action'), action: z.enum(['create', 'update', 'delete']), templateId: idSchema.optional(), data: z.object({ name: z.string().trim().min(1).max(300).optional(), category: z.enum(['reservation', 'collaboration', 'exclusivity', 'custom']).optional(), description: z.string().max(10000).optional(), content: z.string().max(120000).optional(), status: z.enum(['draft', 'active']).optional(), sourceFormat: z.enum(['manual', 'docx']).optional(), fileName: z.string().max(200).optional() }).strict().optional() }).strict(),
  z.object({ kind: z.literal('create_sale'), propertyId: idSchema }).strict(),
  z.object({ kind: z.literal('update_offer'), contactId: idSchema, offerId: idSchema, patch: z.object({ price: z.number().positive().optional(), status: z.enum(['În așteptare', 'Acceptată', 'Refuzată']).optional() }).strict().refine(p => Object.keys(p).length > 0) }).strict(),
  z.object({ kind: z.literal('delete_offer'), contactId: idSchema, offerId: idSchema }).strict(),
  z.object({ kind: z.literal('update_prospect'), listingId: idSchema, patch: z.object({ collaborationStatus: z.enum(['collaborates', 'does_not_collaborate']).nullable().optional(), contactOutcome: z.enum(['negative', 'follow_up']).nullable().optional(), notes: z.string().max(10000).optional(), propertyAddress: z.string().max(1000).optional(), commissionValue: z.string().max(200).optional(), ownerName: z.string().max(200).optional(), ownerPhone: z.string().max(40).optional(), state: z.enum(['reserved', 'taken']).optional() }).strict().refine(p => Object.keys(p).length > 0) }).strict(),
  z.object({ kind: z.literal('portal_action'), contactId: idSchema, action: z.enum(['activate', 'regenerate', 'deactivate', 'remove_recommendation']), propertyId: idSchema.optional() }).strict(),
  z.object({ kind: z.literal('notification_action'), action: z.enum(['read', 'unread', 'read_all']), notificationId: idSchema.optional() }).strict(),
  z.object({ kind: z.literal('update_property_status'), propertyId: idSchema, status: z.enum(['Activ', 'Inactiv', 'Rezervat', 'Vândut', 'Închiriat']), reason: z.enum(['reservation_offer_accepted', 'reservation_financing_pending', 'reservation_documents_pending', 'sale_completed', 'sale_cash', 'sale_financed']).optional(), notes: z.string().max(3000).default(''), soldPrice: z.number().positive().max(1e9).optional() }).strict(),
  z.object({ kind: z.literal('add_property_note'), propertyId: idSchema, notes: z.string().trim().min(1).max(10000) }).strict(),
  z.object({ kind: z.literal('set_property_featured'), propertyId: idSchema, featured: z.boolean() }).strict(),
  z.object({ kind: z.literal('delete_task'), taskId: idSchema }).strict(),
  z.object({ kind: z.literal('delete_viewing'), viewingId: idSchema }).strict(),
  z.object({ kind: z.literal('create_contact'), name: z.string().trim().min(1).max(200), phone: z.string().max(40).default(''), email: z.string().email().or(z.literal('')).default(''), contactType: z.enum(['Cumparator', 'Client', 'Partener']).default('Cumparator'), status: z.enum(['Nou', 'Contactat', 'Vizionare', 'În negociere', 'Câștigat', 'Pierdut']).optional(), priority: z.enum(['Scăzută', 'Medie', 'Ridicată']).optional(), tags: z.array(z.string().max(80)).max(30).optional(), budget: z.number().nonnegative().optional(), city: z.string().max(100).optional(), zones: z.array(z.string().max(100)).max(30).optional(), description: z.string().max(10000).optional(), source: z.string().max(200).optional(), sourcePropertyId: idSchema.nullable().optional(), agentId: idSchema.nullable().optional() }).strict(),
  z.object({ kind: z.literal('archive_contact'), contactId: idSchema, archived: z.boolean(), byAge: z.boolean().optional() }).strict(),
  z.object({ kind: z.literal('assign_record'), resource: z.enum(['contacts', 'properties', 'tasks']), id: idSchema, agentId: idSchema.nullable() }).strict(),
  z.object({ kind: z.literal('create_property'), propertyId: idSchema.optional(), agentId: idSchema.nullable().optional(), statusChange: propertyLifecycleSchema.optional(), property: z.object({ ...propertyExtraFields, title: z.string().trim().min(1).max(300), address: z.string().trim().min(1).max(500), location: z.string().trim().min(1).max(500), city: z.string().max(100).optional(), zone: z.string().max(100).optional(), price: z.number().positive().max(1e9), rooms: z.number().int().nonnegative().max(100), bathrooms: z.number().int().nonnegative().max(100), squareFootage: z.number().positive().max(1e7), propertyType: z.string().trim().min(1).max(100), transactionType: z.string().trim().min(1).max(100), description: z.string().max(20000).default(''), images: z.array(z.object({ url: z.string().url(), alt: z.string().max(500) }).strict()).max(40).default([]) }).strict() }).strict(),
  z.object({ kind: z.literal('update_contact'), contactId: idSchema, expectedUpdatedAt: z.string().datetime({ offset: true }).nullable().optional(), patch: contactPatch.refine(p => Object.keys(p).length > 0) }).strict(),
  z.object({ kind: z.literal('update_preferences'), contactId: idSchema, preferences: preferences.refine(p => Object.keys(p).length > 0) }).strict(),
  z.object({ kind: z.literal('update_property'), propertyId: idSchema, agentId: idSchema.nullable().optional(), expectedUpdatedAt: z.string().datetime({ offset: true }).nullable().optional(), statusChange: propertyLifecycleSchema.optional(), patch: propertyPatch.refine(p => Object.keys(p).length > 0) }).strict(),
  z.object({ kind: z.literal('import_owner_listing'), listingId: idSchema }).strict(),
  z.object({ kind: z.literal('activate_property'), propertyId: idSchema }).strict(),
  z.object({ kind: z.literal('record_offer'), contactId: idSchema, propertyId: idSchema, price: z.number().positive().max(1e9) }).strict(),
  z.object({ kind: z.literal('add_interaction'), contactId: idSchema, notes: z.string().trim().min(1).max(10000), type: z.enum(['Apel telefonic', 'Email', 'WhatsApp', 'Notiță', 'Întâlnire', 'Vizionare', 'Ofertă']).default('Notiță') }).strict(),
  z.object({ kind: z.literal('create_task'), agentId: idSchema.nullable().optional(), ...taskDetails, description: z.string().trim().min(1).max(2000), dueDate: taskDate, contactId: idSchema.optional(), propertyId: idSchema.optional() }).strict(),
  z.object({ kind: z.literal('update_task'), ...taskDetails, taskId: idSchema, status: z.enum(['open', 'completed']).optional(), description: z.string().trim().min(1).max(2000).optional(), dueDate: taskDate.optional(), contactId: idSchema.nullable().optional(), propertyId: idSchema.nullable().optional() }).strict(),
  z.object({ kind: z.literal('schedule_viewing'), agentId: idSchema.optional(), contactId: idSchema, propertyId: idSchema, viewingDate: date, duration: z.number().int().min(15).max(240).default(60), notes: z.string().max(3000).default('') }).strict(),
  z.object({ kind: z.literal('update_viewing'), agentId: idSchema.optional(), viewingId: idSchema, status: z.enum(['scheduled', 'completed', 'cancelled']), contactId: idSchema.optional(), propertyId: idSchema.optional(), viewingDate: date.optional(), duration: z.number().int().min(15).max(240).optional(), notes: z.string().max(3000).optional() }).strict(),
  z.object({ kind: z.literal('recommend_properties'), contactId: idSchema, propertyIds: z.array(idSchema).min(1).max(30) }).strict(),
  z.object({ kind: z.literal('create_automation'), automation: automationSchema }).strict(),
  z.object({ kind: z.literal('update_automation'), automationId: idSchema, status: z.enum(['active', 'paused']).optional(), automation: automationSchema.optional() }).strict(),
  z.object({ kind: z.literal('existing_operation'), operation: idSchema, params: z.record(z.string().max(180)).default({}), query: z.record(z.string().max(2000)).default({}), body: z.record(z.unknown()).default({}) }).strict(),
]);
export type AssistantAction = z.infer<typeof actionSchema>;
export type AssistantSearch = z.infer<typeof searchSchema>;
export type AssistantRead = z.infer<typeof readSchema>;
export type StructuredOutputType = 'TEXT' | 'PROPERTY_CARD' | 'PROPERTY_LIST' | 'PROPERTY_MATCH_LIST' | 'CLIENT_CARD' | 'CLIENT_LIST' | 'VIEWING_CARD' | 'TASK_CARD' | 'CAMPAIGN_CARD' | 'CONFIRMATION_CARD' | 'ACTION_RESULT' | 'PROGRESS_EVENT' | 'ERROR_EVENT' | 'INSIGHT_CARD' | 'ANALYTICS_CARD';
export type AssistantCard = { note?: string | null; scoreMayBeStale?: boolean; freshness?: string; type: 'results' | 'data'; outputType?: StructuredOutputType; resultSetId?: string; title: string; source: string; rows: Record<string, unknown>[]; nextCursor?: string | null; search?: AssistantSearch; complete?: boolean; summary?: { count: number; label: string; period?: string; scope?: string }; query?: z.infer<typeof queryRecordsSchema>; timeline?: z.infer<typeof import('./timeline').timelineSchema> };
export type AccessReference = { resource: 'sales' | 'conversations' | 'socialPosts' | 'salesTemplateAudit' | 'assistantAutomations'; id: string };
export type AssistantMessage = { id: string; role: 'user' | 'assistant'; outputType?: StructuredOutputType; text: string; createdAt: string; cards?: AssistantCard[]; planId?: string; actions?: AssistantAction[]; accessRefs?: AccessReference[] };
export type AssistantPlan = { id: string; outputType?: 'CONFIRMATION_CARD' | 'ACTION_RESULT'; status: 'pending' | 'running' | 'paused' | 'completed' | 'failed' | 'unknown' | 'cancelled'; actions: AssistantAction[]; risks?: string[]; externalCostNote?: string; results?: Record<string, unknown>[]; stoppedStep?: { step: number; result: Record<string, unknown> }; error?: string; createdAt: string };

// Never send integration credentials to a model, browser or persisted result card.
export function safeData(value: unknown, depth = 0): any {
  if (depth > 10) return '[nested]';
  if (value === null || typeof value !== 'object') return value ?? null;
  if (typeof (value as { toDate?: unknown }).toDate === 'function') return (value as { toDate(): Date }).toDate().toISOString();
  if (Array.isArray(value)) return value.map(v => safeData(v, depth + 1));
  return Object.fromEntries(Object.entries(value as Record<string, unknown>).filter(([key]) => !/token|secret|password|credential|privatekey|apikey|authorization/i.test(key)).map(([key, v]) => [key, safeData(v, depth + 1)]));
}
export function normalized(value: unknown) { return String(value ?? '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/\s+/g, ' ').trim(); }
export function overlaps(start: string, duration: number, otherStart: string, otherDuration = 60) {
  const a = Date.parse(start), b = Date.parse(otherStart);
  return a < b + otherDuration * 60000 && b < a + duration * 60000;
}
