import { viewingConfirmationDraftSchema } from './viewing-confirmation-draft';
import { viewingAttendanceSchema } from './viewing-attendance';
import { viewingRiskSchema } from './viewing-risk';
import { calendarAvailabilitySchema } from './calendar-availability';
import { taskDeferralSchema } from './task-deferral';
import { taskPrioritiesSchema } from './task-priorities';
import { taskAgendaSchema } from './task-agenda';
import { viewingFollowupsSchema } from './viewing-followups';
import { propertyViewingsSchema } from './property-viewings';
import { viewingDetailsSchema } from './viewing-details';
import { shiftDatetimeSchema } from './datetime';
import { MAX_PLAN_ACTIONS } from './plan-limits';
import { z } from 'zod';
import { actionSchema, readSchema, relatedSchema, fieldSchema, searchSchema, idSchema, queryRecordsSchema } from './contracts';
import { analysisSchema, datetimeSchema } from './deterministic-contracts';
import { timelineSchema } from './timeline';
import { preferenceKeySchema } from './preferences';
import { goalCoverageSchema } from './goal-coverage';
import { contextSelectionSchema } from './context-selection-contract';
import { matchingRecipientSchema } from './matching-recipient-contract';
const objectOutput = z.record(z.unknown());
const rowsOutput = z.object({ rows: z.array(z.record(z.unknown())) }).passthrough();
const operationInput = z.object({ operation: idSchema, params: z.record(z.string().max(180)).default({}), query: z.record(z.string().max(2000)).default({}), body: z.record(z.unknown()).default({}) }).strict();
export const coreToolSchemas = {
  viewing_risk: [viewingRiskSchema, rowsOutput, 'Pentru care dintre ele au risc mai mare de no-show: compară lista de vizionări afișată anterior, recitind CRM și răspunsurile WhatsApp actuale. Fără parametri/ID-uri presupuse. Explică reasons, priority și viewingLocal, fără procente sau probabilități inventate. unknown nu este refuz; refuzul proprietarului afectează accesul. Explică excluded și limitează concluziile la această listă. needs_clarification cere lista, fără căutare arbitrară. Nu modifică și nu trimite mesaje.'],
  viewing_attendance: [viewingAttendanceSchema, rowsOutput, 'Vizionări neconfirmate ale agentului: dayOffset=1 pentru mâine. Verifică separat clientul și proprietarul, pe date actuale. Lipsa confirmării în CRM NU dovedește refuzul sau neprezentarea. Citește toate paginile nextCursor; complete=false nu este rezultat integral. Afișează viewingLocal și stările participanților. Nu modifica programările.'],
  viewing_confirmation_draft: [viewingConfirmationDraftSchema, rowsOutput, 'Pregătește mesajul de confirmare pentru vizionarea selectată: recipient=client sau owner. Citește vizionarea și datele actuale CRM, separă numele/telefonul proprietarului de client, ora exclusiv București. Afișează description integral ca mesaj pregătit și netrimis; semnalează missingFields fără să inventezi datele lipsă. Nu propune acțiuni de trimitere, nu confirmă participarea, nu modifică CRM. Pentru status diferit de prepared explică datele/starea lipsă și cere clarificare. ID-ul selectat din context poate fi transmis direct, fără read suplimentar.'],
  calendar_availability: [calendarAvailabilitySchema, rowsOutput, 'Intervale libere în calendarul CRM, București, agent curent. fromTime obligatoriu; mâine implicit; untilTime implicit 24:00. duration=1 pentru toate golurile; pentru vizionare durata cerută sau 60 și contactId/propertyId verificate. Afișează startLocal/endLocal, limitele window și scope. Numai complete=true certifică disponibilitatea citită. Pentru primul interval potrivit propune suggestedViewing integral; firstAvailable autorizează recalcularea în aceeași fereastră la salvare. Datele și ID-urile explicite sunt verificate aici pe server, inclusiv clientul/proprietatea. Trimite direct ID-urile din context, fără read redundant. suggestedViewing este contractul complet: copiază-l în propose_actions fără operation_contract suplimentar.'],
  task_deferral: [taskDeferralSchema, rowsOutput, 'Pregătește datele pentru mutarea taskurilor neurgente mâine, fără scrieri. Folosește apoi UN propose_actions cu TOATE suggestedTask, fără schimbarea câmpurilor. dueDate este verificată de server. Exclude taskurile urgente, asociate vizionărilor de azi, deja mâine sau cu date insuficiente. Păstrează ora și durata. Explică excluded și nu pregăti nimic dacă complete=false.'],
  task_priorities: [taskPrioritiesSchema, rowsOutput, 'Recomandă prioritizarea taskurilor proprii, numai open, fără scrieri. mode=urgent pentru urgente, commercial pentru impact comercial. Păstrează ordinea rank și explică reasons/urgencyReasons și criteriile method; nu inventa venituri/probabilități sau un model predictiv. Continuă nextCursor; partial nu certifică ordinea globală. Datele actuale ale clientului/proprietății/vizionării sunt citite din CRM; missingRelations sunt lipsuri, nu dovezi negative.'],
  task_agenda: [taskAgendaSchema, rowsOutput, 'Taskuri ale agentului curent: today pentru scadente azi, overdue pentru restante (ziua scadenței înainte de azi), numai open. Include și sarcini vechi; datele fără oră și instanții ISO sunt interpretați în București. Afișează dueLocal. Continuă nextCursor până la complete; invalidDates semnalează date neclasificabile, nu sarcini rezolvate.'],
  viewing_followups: [viewingFollowupsSchema, objectOutput, 'Afișează orele din viewingLocal, exclusiv București, nu orele UTC din viewingDate. Vizionări efectuate fără task follow-up legat prin viewingId. Agentul curent implicit; dayOffset=-1 pentru ieri, omite pentru tot istoricul. Citește toate paginile. Pentru crearea follow-up-urilor folosește propose_actions o singură dată, cu toate suggestedTask ca actions și kind=create_task pe fiecare. Păstrează viewingId și relațiile. dueDate este deja verificată pe server; copiază data fără oră, fără resolve_datetime suplimentar. Data implicită este azi, fără oră; nu inventa o programare orară. Nu execută scrieri. Nu certifică lipsa contactării manuale sau a sarcinilor vechi fără legătură.'],
  property_viewings: [propertyViewingsSchema, objectOutput, 'Rezolvă mai întâi proprietatea prin read resource=properties search=nume/loc distinctiv, fără presupuneri de tranzacție/status. Istoricul unei proprietăți CRM identificate: all pentru toate vizionările, completed pentru cine a vizionat, count_completed pentru de câte ori a fost vizionată, latest_completed pentru ultima vizită efectuată. Include toți agenții. Numai completed în trecut dovedesc o vizită. Citește numele actuale ale clienților. Pentru liste continuă cu nextCursor până la complete=true; count este totalul. tied_latest păstrează toate vizitele simultane. partial nu certifică totalul/ultima vizită.'],
  viewing_details: [viewingDetailsSchema, objectOutput, 'Identifică o vizionare și citește clientul/proprietatea actuale: contactPhone este telefonul cumpărătorului, ownerPhone al proprietarului din proprietatea CRM. mode=selected cu viewingId; mode=at_time cu time HH:mm și date sau dayOffset (implicit azi); mode=next folosește ora serverului. Pentru at_time/next agentId implicit este agentul curent. status=needs_clarification cere alegerea, partial nu confirmă selecția. Nu substitui telefoanele lipsă și nu confunda proprietarul cu cumpărătorul.'],
  resolve_matching_recipient: [matchingRecipientSchema, rowsOutput, 'Pentru trimite-i a doua proprietate: rezolvă poziția din matchingul salvat și conversațiile asociate exact clientului acelui set. Fără selecție după nume/telefon. conversationId opțional alege explicit o conversație. Nu ghici când recipientStatus=needs_clarification sau recipientSearchComplete=false. Doar citire; resolved nu înseamnă eligibil pentru trimitere. Folosește ulterior message_send cu body.matchingSelection copiat integral din rezultatul resolverului și text concret, în planul cu preview și aprobare.'],
  integration_status: [z.object({ provider: z.enum(['facebook_groups', 'meta_ads', 'tiktok_ads', 'tiktok_organic', 'imobiliare', 'storia', 'romimo', 'communications']) }).strict(), objectOutput, 'Verifică statusul conexiunii alese. NU listează capabilitățile TikTok Ads: pentru acestea apelează existing_read cu operation=tiktok_capabilities. Facebook Groups, Meta Ads, TikTok Ads și TikTok organic sunt integrări distincte. Doar citire; nu conectează și nu publică.'],
  search_global: [z.object({ query: z.string().trim().min(2).max(300) }).strict(), objectOutput, 'Caută global în CRM prin handlerul existent: contacte, proprietăți și sarcini. Nu restrânge cererea globală la o singură colecție.'],
  select_context: [contextSelectionSchema, rowsOutput, 'Rezolvă prima/a treia/primele două înregistrări dintr-o listă afișată, folosind pozițiile salvate și citiri actuale autorizate. messageId/resultSetId/source aleg lista din summary.selections. Nu ghici lista când există mai multe.'],
  goal_coverage: [goalCoverageSchema, objectOutput, 'Leagă TOATE cerințele din cererea curentă de pașii propuși sau de citiri reușite. Apelează după propunerea pașilor, înainte de răspunsul final. sourceQuote este citat exact din cererea utilizatorului; evidenceCallIds sunt ID-uri reale ale apelurilor de citire. Marchează explicit cerințele nesuportate sau care necesită clarificare.'],
  knowledge_search: [z.object({ query: z.string().min(1).max(500), limit: z.number().int().min(1).max(5).default(3) }).strict(), rowsOutput, 'Recuperează playbook-uri imobiliare interne relevante. Nu sunt surse de drept sau fapte despre CRM.'],
  legal_source_search: [z.object({ query: z.string().min(3).max(300), cursor: idSchema.optional() }).strict(), rowsOutput, 'Caută în versiunile oficiale deja arhivate ale agenției. Nu certifică forma juridică în vigoare. Paginează cu nextCursor; pentru text folosește legal_source_read cu URL și snapshotId.'],
  legal_source_read: [z.object({ snapshotId: idSchema.optional(), url: z.string().url().max(2000), offset: z.number().int().min(0).max(1000000).default(0) }).strict(), objectOutput, 'Citește HTML, text sau PDF cu text selectabil dintr-un URL oficial HTTPS cunoscut: legislatie.just.ro, www.ancpi.ro, www.anaf.ro, mfinante.gov.ro, www.uniuneanotarilor.ro, monitoruloficial.ro. Fără redirect/OCR; maximum 1 MiB, PDF maximum 100 pagini și 200000 caractere. Returnează sursa, hashul, data preluării și text paginat pe snapshotId fix; NU certifică versiunea în vigoare. Nu inventa URL-uri/articole și nu afirma lege actuală dacă verificarea temporală lipsește.'],
  data_catalog: [z.object({ category: z.string().max(100).default('') }).strict(), objectOutput, 'Descoperă resursele CRM, relațiile, citirile și limitele de actualitate. Nu încarcă datele agenției în prompt.'],
  capability_status: [z.object({ operation: idSchema }).strict(), objectOutput, 'Verifică drepturi, feature flags, worker și pașii de eligibilitate/provider ai unei capabilități înainte de execuție. Nu confundă înregistrarea cu disponibilitatea integrării.'],
  timeline: [timelineSchema, rowsOutput, 'Istoric autorizat al clientului/proprietății/dosarului/conversației/apelului; paginare și surse explicite.'],
  analyze_records: [analysisSchema, rowsOutput, 'Filtrare, sortare și statistici deterministe pe ID-uri autorizate deja identificate. Nu este un total al agenției.'],
  shift_datetime: [shiftDatetimeSchema, objectOutput, 'Deplasează un ISO verificat cu minutes minute (pozitiv = mai târziu, negativ = mai devreme). Returnează ISO și ora Europe/Bucharest, inclusiv peste schimbarea DST.'],
  resolve_datetime: [datetimeSchema, objectOutput, 'Dată și oră convertite determinist în ISO, exclusiv Europe/Bucharest. Alege exact unul: date, dayOffset (mâine=1) sau weekday (monday..sunday; vineri=friday), plus time HH:mm. weekday alege următoarea apariție la ora cerută, inclusiv azi dacă ora nu a trecut. Detectează ambiguitatea DST.'],
  read: [readSchema, rowsOutput, 'Citește înregistrări autorizate, cu paginare.'],
  query_records: [queryRecordsSchema, rowsOutput, 'Filtrează CRM PE SERVER și numără prin agregare. sales numără numai dosarele autorizate ca agent/colaborator sau administrator; filtrează etapa cu stage, nu status; datele Sales folosesc createdAt. countScope=query indică totalul interogării; countScope=segment este numărul din porțiunea scanată, nu totalul agenției. Nu prezenta un count segment drept total chiar dacă nextCursor=null. Pentru câte vizionări mâine: resource=viewings, dayOffset=1, mode=count. Pentru liste folosește mode=list și nextCursor până la final. Datele relative folosesc timezone explicit, apoi preferința agentului, apoi Europe/Bucharest; cursorul expiră când ziua relativă, fusul sau rolul se schimbă.'],
  read_related: [relatedSchema, rowsOutput, 'Documente, mesaje și audit ale unei resurse autorizate.'],
  read_field: [fieldSchema, objectOutput, 'Citește câmpuri mari în porții, fără secrete.'],
  search_properties: [searchSchema, rowsOutput, 'Căutare de oferte eligibile, cu tip de tranzacție obligatoriu; nu este căutare de identitate/istoric CRM. Pentru identificarea unei proprietăți existente după nume/loc folosește read resource=properties search, inclusiv inactive și fără filtre comerciale. Caută proprietari implicit sau CRM explicit. yearMin/yearMax sunt inclusive: după 1977 înseamnă yearMin=1978, înainte de 1990 yearMax=1989. roomsAny pentru două sau trei camere, fără rooms simultan. unknownYear=include include și rezultate cu dovezi insuficiente pentru filtru, marcate yearFilterSatisfied=false; only caută lipsa anului sau intervalului declarat. Intervalele declarate în câmpul anului, inclusiv after_1977/după 1977, nu devin ani exacți: constructionYearEvidenceKind și limitele păstrează dovada. yearLabel=after_1977 cere explicit eticheta declarată după 1977, nu orice an numeric ulterior. Un interval satisface filtrul numai dacă este inclus integral. Suprapunerea parțială rămâne neconfirmată, iar renovarea nu este an de construcție. Nu prezenta necunoscutele drept potriviri confirmate ale filtrului de an. excludeImported=true elimină importurile CRM prin ID anunț sau URL sursă exact, în agenția curentă. Raportează limita crmComparison: nu certifică absența duplicatelor semantice/manuale fără referință.'],
  match_contact: [z.object({ contactId: idSchema, limit: z.number().int().min(1).max(100).default(30) }).strict(), rowsOutput, 'Preia exclusiv matching-ul existent ImoDeus.'],
  match_property: [z.object({ propertyId: idSchema, limit: z.number().int().min(1).max(100).default(30) }).strict(), rowsOutput, 'Cumpărători potriviți prin algoritmul existent ImoDeus.'],
  filter_existing_matches: [z.object({ resultSetId: idSchema, priceMax: z.number().positive().optional(), zone: z.string().max(100).optional(), limit: z.number().int().min(1).max(100).default(5), sortBy: z.enum(['existing_order', 'score', 'price']).default('existing_order') }).strict(), rowsOutput, 'Filtrează setul existent fără recalculare; păstrează ordinea ImoDeus implicit. sortBy score/price numai dacă se cere explicit.'],
  operation_contract: [z.object({ operation: idSchema, actionKind: idSchema.optional() }).strict(), objectOutput, 'Schema unui instrument sau handler existent.'],
  parallel_read: [z.object({ calls: z.array(z.object({ operation: z.enum(['read', 'read_related', 'search_properties', 'match_contact', 'match_property', 'insights']), payload: z.record(z.unknown()) }).strict()).min(1).max(3) }).strict(), objectOutput, 'Execută maximum trei citiri independente în paralel. payload este JSON {"calls":[{"operation":"read","payload":{"resource":"contacts","limit":10}}]}. Operații permise: read, read_related, search_properties, match_contact, match_property, insights. Pentru query_records sau search_global folosește direct instrumentele respective.'],
  discover_tools: [z.object({ category: z.string().max(60).default(''), cursor: z.number().int().nonnegative().default(0), limit: z.number().int().min(1).max(20).default(12) }).strict(), objectOutput, 'Descoperă handler-ele pe categorii; schema se cere separat.'],
  existing_read: [operationInput, objectOutput, 'Apelează numai handler-ele readOnly autorizate.'],
  propose_actions: [z.object({ actions: z.array(actionSchema).min(1).max(MAX_PLAN_ACTIONS) }).strict(), objectOutput, 'Pregătește acțiuni; nu execută. Obligatoriu payload este JSON {"actions":[{"kind":"...",...}]}, inclusiv pentru o singură acțiune. Consultă operation_contract pentru schema acțiunii.'],
  remember_preference: [z.object({ key: preferenceKeySchema, value: z.string().trim().min(1).max(200) }).strict(), objectOutput, 'Salvează numai preferința cerută explicit; nu date CRM. Preferința pentru brief nu activează livrarea sau o automatizare.'],
  forget_preference: [z.object({ key: preferenceKeySchema }).strict(), objectOutput, 'Șterge exclusiv preferința proprie, numai la cererea explicită a agentului.'],
  delegate_read: [z.object({ goal: z.string().min(1).max(1000), tools: z.array(z.enum(['read', 'read_related', 'search_properties', 'filter_existing_matches', 'read_field', 'existing_read', 'discover_tools', 'insights', 'analyze_records'])).min(1).max(3), resultSetId: idSchema.optional() }).strict(), objectOutput, 'Subagent limitat la citiri, cu același tenant și buget comun; fără recalculare matching.'],
  insights: [z.object({ limit: z.number().int().min(1).max(30).default(10) }).strict(), rowsOutput, 'Insight-uri deterministe din toate paginile citite pe server (max 5000 înregistrări/sursă), fără limita UI de 100. Respectă complete=false și continuations; actionableCount parțial nu este totalul agenției. payload={limit: numărul de carduri, 1..30}.'],
  mcp_discover: [z.object({ serverId: idSchema }).strict(), objectOutput, 'Descoperă tools externe read-only explicit autorizate agenției.'],
  mcp_read: [z.object({ serverId: idSchema, tool: idSchema, arguments: z.record(z.unknown()).default({}) }).strict(), objectOutput, 'Tool MCP read-only allowlisted; fără URL-uri sau servere din prompt.'],
} as const;
export const actionToolSchemas = Object.fromEntries(actionSchema.options.filter(schema => !['existing_operation'].includes(schema.shape.kind.value)).map(schema => [schema.shape.kind.value, [(schema as z.AnyZodObject).omit({ kind: true }), objectOutput, `Pregătește ${schema.shape.kind.value} în planul confirmabil. Nu execută direct. ID-uri reale sau @step:N:contactId. Nu refuza o acțiune disponibilă.`] as const]));
