import { MAX_PLAN_ACTIONS } from './plan-limits';
import { z } from 'zod';
import { actionSchema, readSchema, relatedSchema, fieldSchema, searchSchema, idSchema, queryRecordsSchema } from './contracts';
import { analysisSchema, datetimeSchema } from './deterministic-contracts';
import { timelineSchema } from './timeline';
import { preferenceKeySchema } from './preferences';
import { goalCoverageSchema } from './goal-coverage';
import { contextSelectionSchema } from './context-selection-contract';
const objectOutput = z.record(z.unknown());
const rowsOutput = z.object({ rows: z.array(z.record(z.unknown())) }).passthrough();
const operationInput = z.object({ operation: idSchema, params: z.record(z.string().max(180)).default({}), query: z.record(z.string().max(2000)).default({}), body: z.record(z.unknown()).default({}) }).strict();
export const coreToolSchemas = {
  integration_status: [z.object({ provider: z.enum(['facebook_groups', 'meta_ads', 'tiktok_ads', 'tiktok_organic', 'imobiliare', 'storia', 'romimo', 'communications']) }).strict(), objectOutput, 'Verifică statusul conexiunii alese. NU listează capabilitățile TikTok Ads: pentru acestea apelează existing_read cu operation=tiktok_capabilities. Facebook Groups, Meta Ads, TikTok Ads și TikTok organic sunt integrări distincte. Doar citire; nu conectează și nu publică.'],
  search_global: [z.object({ query: z.string().trim().min(2).max(300) }).strict(), objectOutput, 'Caută global în CRM prin handlerul existent: contacte, proprietăți și sarcini. Nu restrânge cererea globală la o singură colecție.'],
  select_context: [contextSelectionSchema, rowsOutput, 'Rezolvă prima/a treia/primele două înregistrări dintr-o listă afișată, folosind pozițiile salvate și citiri actuale autorizate. messageId/resultSetId/source aleg lista din summary.selections. Nu ghici lista când există mai multe.'],
  goal_coverage: [goalCoverageSchema, objectOutput, 'Leagă TOATE cerințele din cererea curentă de pașii propuși sau de citiri reușite. Apelează după propunerea pașilor, înainte de răspunsul final. sourceQuote este citat exact din cererea utilizatorului; evidenceCallIds sunt ID-uri reale ale apelurilor de citire. Marchează explicit cerințele nesuportate sau care necesită clarificare.'],
  knowledge_search: [z.object({ query: z.string().min(1).max(500), limit: z.number().int().min(1).max(5).default(3) }).strict(), rowsOutput, 'Recuperează playbook-uri imobiliare interne relevante. Nu sunt surse de drept sau fapte despre CRM.'],
  legal_source_search: [z.object({ query: z.string().min(3).max(300), cursor: idSchema.optional() }).strict(), rowsOutput, 'Caută în versiunile oficiale deja arhivate ale agenției. Nu certifică forma juridică în vigoare. Paginează cu nextCursor; pentru text folosește legal_source_read cu URL și snapshotId.'],
  legal_source_read: [z.object({ snapshotId: idSchema.optional(), url: z.string().url().max(2000), offset: z.number().int().min(0).max(1000000).default(0) }).strict(), objectOutput, 'Citește HTML, text sau PDF cu text selectabil dintr-un URL oficial HTTPS cunoscut: legislatie.just.ro, www.ancpi.ro, www.anaf.ro, mfinante.gov.ro, www.uniuneanotarilor.ro, monitoruloficial.ro. Fără redirect/OCR; maximum 1 MiB, PDF maximum 100 pagini și 200000 caractere. Returnează sursa, hashul, data preluării și text paginat pe snapshotId fix; NU certifică versiunea în vigoare. Nu inventa URL-uri/articole și nu afirma lege actuală dacă verificarea temporală lipsește.'],
  data_catalog: [z.object({ category: z.string().max(100).default('') }).strict(), objectOutput, 'Descoperă resursele CRM, relațiile, citirile și limitele de actualitate. Nu încarcă datele agenției în prompt.'],
  capability_status: [z.object({ operation: idSchema }).strict(), objectOutput, 'Verifică drepturi, feature flags, worker și pașii de eligibilitate/provider ai unei capabilități înainte de execuție. Nu confundă înregistrarea cu disponibilitatea integrării.'],
  timeline: [timelineSchema, rowsOutput, 'Istoric autorizat al clientului/proprietății/dosarului/conversației/apelului; paginare și surse explicite.'],
  analyze_records: [analysisSchema, rowsOutput, 'Filtrare, sortare și statistici deterministe pe ID-uri autorizate deja identificate. Nu este un total al agenției.'],
  resolve_datetime: [datetimeSchema, objectOutput, 'Dată și oră convertite determinist în ISO; timezone IANA opțional, implicit preferința timezone a agentului sau Europe/Bucharest. Detectează ambiguitatea DST. date sau dayOffset (mâine=1), time HH:mm.'],
  read: [readSchema, rowsOutput, 'Citește înregistrări autorizate, cu paginare.'],
  query_records: [queryRecordsSchema, rowsOutput, 'Filtrează CRM PE SERVER și numără prin agregare. sales numără numai dosarele autorizate ca agent/colaborator sau administrator; filtrează etapa cu stage, nu status; datele Sales folosesc createdAt. countScope=query indică totalul interogării; countScope=segment este numărul din porțiunea scanată, nu totalul agenției. Nu prezenta un count segment drept total chiar dacă nextCursor=null. Pentru câte vizionări mâine: resource=viewings, dayOffset=1, mode=count. Pentru liste folosește mode=list și nextCursor până la final. Datele relative folosesc timezone explicit, apoi preferința agentului, apoi Europe/Bucharest; cursorul expiră când ziua relativă, fusul sau rolul se schimbă.'],
  read_related: [relatedSchema, rowsOutput, 'Documente, mesaje și audit ale unei resurse autorizate.'],
  read_field: [fieldSchema, objectOutput, 'Citește câmpuri mari în porții, fără secrete.'],
  search_properties: [searchSchema, rowsOutput, 'Caută proprietari implicit sau CRM explicit.'],
  match_contact: [z.object({ contactId: idSchema, limit: z.number().int().min(1).max(100).default(30) }).strict(), rowsOutput, 'Preia exclusiv matching-ul existent ImoDeus.'],
  match_property: [z.object({ propertyId: idSchema, limit: z.number().int().min(1).max(100).default(30) }).strict(), rowsOutput, 'Cumpărători potriviți prin algoritmul existent ImoDeus.'],
  filter_existing_matches: [z.object({ resultSetId: idSchema, priceMax: z.number().positive().optional(), zone: z.string().max(100).optional(), limit: z.number().int().min(1).max(100).default(5), sortBy: z.enum(['existing_order', 'score', 'price']).default('existing_order') }).strict(), rowsOutput, 'Filtrează setul existent fără recalculare; păstrează ordinea ImoDeus implicit. sortBy score/price numai dacă se cere explicit.'],
  operation_contract: [z.object({ operation: idSchema, actionKind: idSchema.optional() }).strict(), objectOutput, 'Schema unui instrument sau handler existent.'],
  parallel_read: [z.object({ calls: z.array(z.object({ operation: z.enum(['read', 'read_related', 'search_properties', 'match_contact', 'match_property', 'insights']), payload: z.record(z.unknown()) }).strict()).min(1).max(3) }).strict(), objectOutput, 'Execută maximum trei citiri independente în paralel.'],
  discover_tools: [z.object({ category: z.string().max(60).default(''), cursor: z.number().int().nonnegative().default(0), limit: z.number().int().min(1).max(20).default(12) }).strict(), objectOutput, 'Descoperă handler-ele pe categorii; schema se cere separat.'],
  existing_read: [operationInput, objectOutput, 'Apelează numai handler-ele readOnly autorizate.'],
  propose_actions: [z.object({ actions: z.array(actionSchema).min(1).max(MAX_PLAN_ACTIONS) }).strict(), objectOutput, 'Pregătește acțiuni; nu execută. Obligatoriu payload este JSON {"actions":[{"kind":"...",...}]}, inclusiv pentru o singură acțiune. Consultă operation_contract pentru schema acțiunii.'],
  remember_preference: [z.object({ key: preferenceKeySchema, value: z.string().trim().min(1).max(200) }).strict(), objectOutput, 'Salvează numai preferința cerută explicit; nu date CRM. Preferința pentru brief nu activează livrarea sau o automatizare.'],
  forget_preference: [z.object({ key: preferenceKeySchema }).strict(), objectOutput, 'Șterge exclusiv preferința proprie, numai la cererea explicită a agentului.'],
  delegate_read: [z.object({ goal: z.string().min(1).max(1000), tools: z.array(z.enum(['read', 'read_related', 'search_properties', 'filter_existing_matches', 'read_field', 'existing_read', 'discover_tools', 'insights', 'analyze_records'])).min(1).max(3), resultSetId: idSchema.optional() }).strict(), objectOutput, 'Subagent limitat la citiri, cu același tenant și buget comun; fără recalculare matching.'],
  insights: [z.object({ limit: z.number().int().min(1).max(30).default(10) }).strict(), rowsOutput, 'Insight-uri deterministe din toate paginile citite pe server (max 5000 înregistrări/sursă), fără limita UI de 100. Respectă complete=false și continuations; actionableCount parțial nu este totalul agenției. payload={limit: numărul de carduri, 1..30}.'],
  mcp_discover: [z.object({ serverId: idSchema }).strict(), objectOutput, 'Descoperă tools externe read-only explicit autorizate agenției.'],
  mcp_read: [z.object({ serverId: idSchema, tool: idSchema, arguments: z.record(z.unknown()).default({}) }).strict(), objectOutput, 'Tool MCP read-only allowlisted; fără URL-uri sau servere din prompt.'],
} as const;
export const actionToolSchemas = Object.fromEntries(actionSchema.options.filter(schema => !['existing_operation'].includes(schema.shape.kind.value)).map(schema => [schema.shape.kind.value, [(schema as z.AnyZodObject).omit({ kind: true }), objectOutput, `Pregătește ${schema.shape.kind.value} în planul confirmabil. Nu execută direct. ID-uri reale sau @step:N:contactId. Nu refuza o acțiune disponibilă.`] as const]));
