'use client';
import { useState } from 'react';
import { useAgency } from '@/context/AgencyContext';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { automationSchema, type AssistantAction } from '@/lib/ai-assistant/contracts';
import type { EventRule } from '@/lib/ai-assistant/event-rules';
type Row = Record<string, any>;
const names: Record<string, string> = { event_rule: 'Regulă CRM', followup_task: 'Follow-up', owner_watch: 'Căutare proprietari', insight_report: 'Raport', matching_watch: 'Matching', whatsapp_template: 'Șablon WhatsApp' };
const resources = { contacts: 'Clienți', properties: 'Proprietăți', viewings: 'Vizionări', sales: 'Dosare', ownerListingFavorites: 'Prospectare' };
const selectClass = 'w-full rounded-md border bg-background px-3 py-2 text-sm';
export function AutomationsPanel({ busy, onPrepare }: { busy: boolean; onPrepare: (actions: AssistantAction[]) => void | Promise<void> }) {
  const { user } = useAgency();
  const [rows, setRows] = useState<Row[]>([]), [cursor, setCursor] = useState<string | null>(null), [opened, setOpened] = useState(false), [loading, setLoading] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const [editing, setEditing] = useState<string | null>(null), [form, setForm] = useState(false), [history, setHistory] = useState<Row[]>([]), [historyTarget, setHistoryTarget] = useState<string | null>(null), [historyCursor, setHistoryCursor] = useState<string | null>(null);
  const [resource, setResource] = useState<EventRule['trigger']['resource']>('contacts'), [change, setChange] = useState<'created' | 'updated'>('updated'), [from, setFrom] = useState(''), [to, setTo] = useState(''), [field, setField] = useState('status'), [recordId, setRecordId] = useState('');
  const [description, setDescription] = useState(''), [title, setTitle] = useState(''), [delay, setDelay] = useState('60'), [interval, setInterval] = useState('30'), [runs, setRuns] = useState('48'), [maxEvents, setMaxEvents] = useState('100');
  const [original, setOriginal] = useState<EventRule | null>(null);
  const request = async (query = '') => {
    if (!user) throw new Error('Autentificare necesară.');
    const response = await fetch('/api/ai-assistant/automations' + query, { headers: { Authorization: 'Bearer ' + await user.getIdToken() }, cache: 'no-store' });
    const data = await response.json(); if (!response.ok) throw new Error(data.message || 'Automatizările nu au putut fi citite.'); return data;
  };
  const perform = async (work: () => Promise<void>) => { setLoading(true); setError(''); try { await work(); } catch (e) { setError(e instanceof Error ? e.message : 'Operația a eșuat.'); } finally { setLoading(false); } };
  const load = (more = false) => perform(async () => { const data = await request(more && cursor ? '?cursor=' + encodeURIComponent(cursor) : ''); setRows(old => more ? [...old, ...data.rows] : data.rows); setCursor(data.nextCursor); setOpened(true); });
  const loadHistory = (id: string, more = false) => perform(async () => { const data = await request('?id=' + encodeURIComponent(id) + (more && historyCursor ? '&cursor=' + encodeURIComponent(historyCursor) : '')); setHistory(old => more ? [...old, ...data.rows] : data.rows); setHistoryCursor(data.nextCursor); setHistoryTarget(id); });
  const prepare = (action: AssistantAction) => perform(async () => { await onPrepare([action]); setNotice('Planul este pregătit pentru verificare și confirmare. Reîmprospătează lista după execuție.'); });
  const edit = (row?: Row) => {
    const rule = row?.automation as EventRule | undefined; setOriginal(rule || null); setEditing(row?.id || null); setForm(true); setNotice('');
    setResource(rule?.trigger.resource || 'contacts'); setChange(rule?.trigger.change || 'updated'); setFrom(rule?.trigger.statusFrom || ''); setTo(rule?.trigger.statusTo || ''); setField(rule?.trigger.changedFields?.[0] || ''); setRecordId(rule?.trigger.recordId || '');
    const task = rule?.effects.find(effect => effect.kind === 'create_task'), notify = rule?.effects.find(effect => effect.kind === 'notify');
    setDescription(task?.kind === 'create_task' ? task.description : ''); setDelay(String(task?.kind === 'create_task' ? task.dueAfterMinutes : 60)); setTitle(notify?.kind === 'notify' ? notify.title : ''); setInterval(String(rule?.intervalMinutes || 30)); setRuns(String(rule?.maxRuns || 48)); setMaxEvents(String(rule?.maxEvents || 100));
  };
  const save = () => perform(async () => {
    const firstRun = new Date(Date.now() + 60000), minutes = Number(interval), runCount = Number(runs);
    const taskIndex = original?.effects.findIndex(effect => effect.kind === 'create_task') ?? -1, notifyIndex = original?.effects.findIndex(effect => effect.kind === 'notify') ?? -1;
    const effects = (original?.effects || []).flatMap((effect, index) => index === taskIndex ? description.trim() ? [{ ...effect, description: description.trim(), dueAfterMinutes: Number(delay) }] : [] : index === notifyIndex ? title.trim() ? [{ ...effect, title: title.trim() }] : [] : [effect]);
    if (taskIndex < 0 && description.trim()) effects.push({ kind: 'create_task', description: description.trim(), dueAfterMinutes: Number(delay) });
    if (notifyIndex < 0 && title.trim()) effects.push({ kind: 'notify', title: title.trim(), body: '' });
    const changedFields = original?.trigger.changedFields?.[0] === field ? original.trigger.changedFields : field ? [field] : undefined;
    const automation = automationSchema.parse({ type: 'event_rule', nextRunAt: firstRun.toISOString(), intervalMinutes: minutes, maxRuns: runCount, maxEvents: Number(maxEvents), stopAfter: new Date(firstRun.getTime() + minutes * runCount * 60000).toISOString(), trigger: { resource, change, ...(recordId.trim() ? { recordId: recordId.trim() } : {}), ...(changedFields ? { changedFields } : {}), ...(from.trim() ? { statusFrom: from.trim() } : {}), ...(to.trim() ? { statusTo: to.trim() } : {}) }, effects });
    await onPrepare([editing ? { kind: 'update_automation', automationId: editing, automation } : { kind: 'create_automation', automation }]); setForm(false); setNotice('Planul regulii este pregătit. Verifică parametrii și confirmă-l în conversație.');
  });
  const disabled = busy || loading || !user;
  return <section className="space-y-3 rounded-3xl border bg-background p-5"><h2 className="font-semibold">Automatizări și reguli CRM</h2><p className="text-xs text-muted-foreground">Rulează cu drepturile tale. Oprește la termen sau la limita de evenimente.</p><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" disabled={disabled} onClick={() => void load()}>Vezi automatizările</Button><Button size="sm" variant="outline" disabled={disabled} onClick={() => edit()}>Regulă nouă</Button></div>
    {error && <p role="alert" className="text-sm text-destructive">{error}</p>}{notice && <p role="status" className="text-xs text-muted-foreground">{notice}</p>}
    {form && <form className="space-y-3 rounded-xl border p-3" onSubmit={e => { e.preventDefault(); void save(); }}>
      <label className="block text-sm">Modul<select className={selectClass} value={resource} onChange={e => setResource(e.target.value as EventRule['trigger']['resource'])}>{Object.entries(resources).map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label>
      <label className="block text-sm">Eveniment<select className={selectClass} value={change} onChange={e => setChange(e.target.value as 'created' | 'updated')}><option value="created">Înregistrare nouă</option><option value="updated">Înregistrare modificată</option></select></label>
      <label className="block text-sm">Câmp urmărit<select className={selectClass} value={field} onChange={e => setField(e.target.value)}><option value="">Orice modificare</option>{['status', 'stage', 'agentId', 'collaborationStatus', 'contactOutcome', 'viewingDate', 'price', 'budget', 'financingType'].map(value => <option key={value} value={value}>{({ status: 'Status', stage: 'Etapă', agentId: 'Agent', collaborationStatus: 'Colaborare', contactOutcome: 'Rezultat prospectare', viewingDate: 'Data vizionării', price: 'Preț', budget: 'Buget', financingType: 'Finanțare' } as Record<string, string>)[value]}</option>)}</select></label>
      <label className="block text-sm">Status anterior (opțional)<Input value={from} onChange={e => setFrom(e.target.value)} maxLength={100} /></label><label className="block text-sm">Status nou (opțional)<Input value={to} onChange={e => setTo(e.target.value)} maxLength={100} /></label><label className="block text-sm">Doar înregistrarea cu ID (opțional)<Input value={recordId} onChange={e => setRecordId(e.target.value)} maxLength={180} /></label>
      <label className="block text-sm">Sarcină de creat (gol = fără sarcină)<Input value={description} onChange={e => setDescription(e.target.value)} maxLength={2000} /></label><label className="block text-sm">Termen după eveniment, minute<Input type="number" min="0" max="43200" value={delay} onChange={e => setDelay(e.target.value)} required /></label><label className="block text-sm">Notificare proprie (gol = fără notificare)<Input value={title} onChange={e => setTitle(e.target.value)} maxLength={200} /></label>
      <label className="block text-sm">Interval verificare, minute<Input type="number" min="30" max="43200" value={interval} onChange={e => setInterval(e.target.value)} required /></label><label className="block text-sm">Maximum verificări<Input type="number" min="1" max="365" value={runs} onChange={e => setRuns(e.target.value)} required /></label><label className="block text-sm">Maximum evenimente<Input type="number" min="1" max="1000" value={maxEvents} onChange={e => setMaxEvents(e.target.value)} required /></label><p className="text-xs text-muted-foreground">Se aplică evenimentelor viitoare. Efectele sunt sarcini și notificări; comunicările externe au flux separat.</p><div className="flex gap-2"><Button size="sm" type="submit" disabled={disabled || (!description.trim() && !title.trim())}>Pregătește regula</Button><Button size="sm" type="button" variant="ghost" onClick={() => setForm(false)}>Închide</Button></div>
    </form>}
    {opened && <div className="max-h-96 space-y-2 overflow-auto">{rows.map(row => <article key={row.id} className="space-y-2 rounded-xl border p-3 text-sm"><strong>{names[row.automation?.type] || 'Automatizare'}</strong><p>{row.status} · {row.runCount || 0} verificări{row.automation?.maxRuns ? ' / ' + row.automation.maxRuns : ''}</p>{row.automation?.trigger && <p>{resources[row.automation.trigger.resource as keyof typeof resources]} · {row.automation.trigger.statusTo || 'evenimente configurate'}</p>}{row.error && <p className="text-destructive">{row.error}</p>}<div className="flex flex-wrap gap-1">{['active', 'paused'].includes(row.status) && <Button size="sm" variant="outline" disabled={disabled} onClick={() => void prepare({ kind: 'update_automation', automationId: row.id, status: row.status === 'active' ? 'paused' : 'active' })}>{row.status === 'active' ? 'Pauză' : 'Reia'}</Button>}{row.automation?.type === 'event_rule' && ['active', 'paused'].includes(row.status) && <Button size="sm" variant="outline" disabled={disabled} onClick={() => edit(row)}>Editează</Button>}<Button size="sm" variant="ghost" disabled={disabled} onClick={() => void loadHistory(row.id)}>Istoric</Button></div></article>)}{!rows.length && <p className="text-sm text-muted-foreground">Nu există automatizări în acest segment.</p>}{cursor && <Button size="sm" variant="outline" disabled={disabled} onClick={() => void load(true)}>Încarcă următoarele</Button>}</div>}
    {historyTarget && <div className="space-y-2 rounded-xl border p-3"><strong className="text-sm">Istoric execuții</strong>{history.map(row => <p key={row.id} className="text-xs">{row.occurredAt} · {row.action} · {row.status || ''}{row.error ? ' · ' + row.error : ''}{row.result?.handled != null ? ' · ' + row.result.handled + ' evenimente executate' : ''}</p>)}{!history.length && <p className="text-xs text-muted-foreground">Nicio execuție în segmentul curent.</p>}{historyCursor && <Button size="sm" variant="outline" disabled={disabled} onClick={() => void loadHistory(historyTarget, true)}>Istoric anterior</Button>}</div>}
  </section>;
}
