'use client';
import { useEffect, useState } from 'react';
import { useAgency } from '@/context/AgencyContext';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { automationSchema, type AssistantAction } from '@/lib/ai-assistant/contracts';
import type { EventRule } from '@/lib/ai-assistant/event-rules';
import { AutomationDefinitionEditor } from './AutomationDefinitionEditor';
type Row = Record<string, any>;
const names: Record<string, string> = { event_rule: 'Regulă CRM', followup_task: 'Follow-up', owner_watch: 'Căutare proprietari', insight_report: 'Raport', matching_watch: 'Matching', whatsapp_template: 'Șablon WhatsApp', daily_sales_brief: 'Prioritățile zilei' };
const deliveryNames: Record<string, string> = { queued: 'În coadă', sending: 'Se trimite', accepted: 'Acceptat de canal', delivered: 'Livrat', read: 'Citit', failed: 'Trimitere eșuată', unknown: 'Livrare neconfirmată' };
const resources = { contacts: 'Clienți', properties: 'Proprietăți', viewings: 'Vizionări', sales: 'Dosare', ownerListingFavorites: 'Prospectare' };
const fieldNames: Record<string, string> = { status: 'Status', stage: 'Etapă', agentId: 'Agent', collaborationStatus: 'Colaborare', contactOutcome: 'Rezultat prospectare', viewingDate: 'Data vizionării', price: 'Preț', budget: 'Buget', financingType: 'Finanțare' };
const trackedFields = ['status', 'stage', 'agentId', 'collaborationStatus', 'contactOutcome', 'viewingDate', 'price', 'budget', 'financingType'] as const;
function localDate(iso?: string) { const date = new Date(iso || Date.now() + 5 * 60000); return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }
const selectClass = 'w-full rounded-md border bg-background px-3 py-2 text-sm';
export function AutomationsPanel({ busy, onPrepare }: { busy: boolean; onPrepare: (actions: AssistantAction[]) => void | Promise<void> }) {
  const { user } = useAgency();
  const [rows, setRows] = useState<Row[]>([]), [cursor, setCursor] = useState<string | null>(null), [opened, setOpened] = useState(false), [loading, setLoading] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const [editing, setEditing] = useState<string | null>(null), [form, setForm] = useState(false), [history, setHistory] = useState<Row[]>([]), [historyTarget, setHistoryTarget] = useState<string | null>(null), [historyCursor, setHistoryCursor] = useState<string | null>(null);
  const [resource, setResource] = useState<EventRule['trigger']['resource']>('contacts'), [change, setChange] = useState<'created' | 'updated'>('updated'), [from, setFrom] = useState(''), [to, setTo] = useState(''), [field, setField] = useState('status'), [recordId, setRecordId] = useState('');
  const [description, setDescription] = useState(''), [title, setTitle] = useState(''), [delay, setDelay] = useState('60'), [interval, setInterval] = useState('30'), [runs, setRuns] = useState('48'), [maxEvents, setMaxEvents] = useState('100');
  const [original, setOriginal] = useState<EventRule | null>(null);
  const [firstRunValue, setFirstRunValue] = useState(''), [stopValue, setStopValue] = useState(''), [taskAgent, setTaskAgent] = useState(''), [notifyBody, setNotifyBody] = useState(''), [additionalFields, setAdditionalFields] = useState<string[]>([]), [extraEffects, setExtraEffects] = useState<EventRule['effects']>([]), [agents, setAgents] = useState<Row[]>([]), [runCountBeforeEdit, setRunCountBeforeEdit] = useState(0);
  useEffect(() => { if (!form || !user) return; const controller = new AbortController(); void (async () => { try { const response = await fetch('/api/agency/agents', { headers: { Authorization: 'Bearer ' + await user.getIdToken() }, signal: controller.signal }); if (!response.ok) throw new Error('Lista agenților nu poate fi citită.'); const data = await response.json(); if (!controller.signal.aborted) setAgents(data.agents || []); } catch (e) { if (!controller.signal.aborted) setError(e instanceof Error ? e.message : 'Citire nereușită.'); } })(); return () => controller.abort(); }, [form, user]);
  const [definitionEditor, setDefinitionEditor] = useState<{ row?: Row } | null>(null);
  const request = async (query = '') => {
    if (!user) throw new Error('Autentificare necesară.');
    const response = await fetch('/api/ai-assistant/automations' + query, { headers: { Authorization: 'Bearer ' + await user.getIdToken() }, cache: 'no-store' });
    const data = await response.json(); if (!response.ok) throw new Error(data.message || 'Automatizările nu au putut fi citite.'); return data;
  };
  const perform = async (work: () => Promise<void>) => { setLoading(true); setError(''); try { await work(); } catch (e) { setError(e instanceof Error ? e.message : 'Operația a eșuat.'); } finally { setLoading(false); } };
  const load = (more = false) => perform(async () => { const data = await request(more && cursor ? '?cursor=' + encodeURIComponent(cursor) : ''); setRows(old => more ? [...old, ...data.rows] : data.rows); setCursor(data.nextCursor); setOpened(true); });
  const loadHistory = (id: string, more = false) => perform(async () => { const data = await request('?id=' + encodeURIComponent(id) + (more && historyCursor ? '&cursor=' + encodeURIComponent(historyCursor) : '')); setHistory(old => more ? [...old, ...data.rows] : data.rows); setHistoryCursor(data.nextCursor); setHistoryTarget(id); });
  const prepare = (action: AssistantAction) => perform(async () => { await onPrepare([action]); setNotice('Planul este pregătit pentru verificare și confirmare. Reîmprospătează lista după execuție.'); });
  const edit = (row?: Row) => {
    setDefinitionEditor(null);
    const rule = row?.automation as EventRule | undefined; setOriginal(rule || null); setEditing(row?.id || null); setForm(true); setNotice('');
    setResource(rule?.trigger.resource || 'contacts'); setChange(rule?.trigger.change || 'updated'); setFrom(rule?.trigger.statusFrom || ''); setTo(rule?.trigger.statusTo || ''); setField(rule?.trigger.changedFields?.[0] || ''); setRecordId(rule?.trigger.recordId || '');
    const task = rule?.effects.find(effect => effect.kind === 'create_task'), notify = rule?.effects.find(effect => effect.kind === 'notify');
    setFirstRunValue(localDate(rule?.nextRunAt)); setStopValue(rule?.stopAfter ? localDate(rule.stopAfter) : ''); setRunCountBeforeEdit(Number(row?.runCount || 0)); setTaskAgent(task?.kind === 'create_task' ? task.agentId || '' : ''); setNotifyBody(notify?.kind === 'notify' ? notify.body : ''); setAdditionalFields(rule?.trigger.changedFields?.slice(1) || []);
    const taskIndex = rule?.effects.findIndex(effect => effect.kind === 'create_task'), notifyIndex = rule?.effects.findIndex(effect => effect.kind === 'notify'); setExtraEffects(rule?.effects.filter((_, index) => index !== taskIndex && index !== notifyIndex) || []);
    setDescription(task?.kind === 'create_task' ? task.description : ''); setDelay(String(task?.kind === 'create_task' ? task.dueAfterMinutes : 60)); setTitle(notify?.kind === 'notify' ? notify.title : ''); setInterval(String(rule?.intervalMinutes || 30)); setRuns(String(rule?.maxRuns || 48)); setMaxEvents(String(rule?.maxEvents || 100));
  };
  const save = () => perform(async () => {
    const nextRunAt = original?.nextRunAt && firstRunValue === localDate(original.nextRunAt) ? original.nextRunAt : new Date(firstRunValue).toISOString(), minutes = Number(interval), runCount = Number(runs);
    const stopAfter = stopValue ? original?.stopAfter && stopValue === localDate(original.stopAfter) ? original.stopAfter : new Date(stopValue).toISOString() : undefined;
    if (Date.parse(nextRunAt) <= Date.now()) throw new Error('Alege următoarea verificare în viitor.');
    if (runCount <= runCountBeforeEdit) throw new Error('Limita trebuie să depășească numărul de verificări deja executate.');
    if (stopAfter && Date.parse(stopAfter) <= Date.parse(nextRunAt)) throw new Error('Oprirea trebuie să fie după prima verificare.');
    const taskIndex = original?.effects.findIndex(effect => effect.kind === 'create_task') ?? -1, notifyIndex = original?.effects.findIndex(effect => effect.kind === 'notify') ?? -1;
    const effects: EventRule['effects'] = (original?.effects || []).flatMap<EventRule['effects'][number]>((effect, index) => index === taskIndex ? description.trim() ? [{ kind: 'create_task' as const, description: description.trim(), dueAfterMinutes: Number(delay), ...(taskAgent ? { agentId: taskAgent } : {}) }] : [] : index === notifyIndex ? title.trim() ? [{ kind: 'notify' as const, title: title.trim(), body: notifyBody }] : [] : []);
    if (taskIndex < 0 && description.trim()) effects.push({ kind: 'create_task', description: description.trim(), dueAfterMinutes: Number(delay), ...(taskAgent ? { agentId: taskAgent } : {}) });
    if (notifyIndex < 0 && title.trim()) effects.push({ kind: 'notify', title: title.trim(), body: notifyBody });
    effects.push(...extraEffects);
    const changedFields = [...new Set([...(field ? [field] : []), ...additionalFields])];
    const automation = automationSchema.parse({ type: 'event_rule', nextRunAt, intervalMinutes: minutes, maxRuns: runCount, maxEvents: Number(maxEvents), ...(stopAfter ? { stopAfter } : {}), ...(original?.stopOnContactStatuses ? { stopOnContactStatuses: original.stopOnContactStatuses } : {}), trigger: { resource, change, ...(recordId.trim() ? { recordId: recordId.trim() } : {}), ...(changedFields.length ? { changedFields } : {}), ...(from.trim() ? { statusFrom: from.trim() } : {}), ...(to.trim() ? { statusTo: to.trim() } : {}) }, effects });
    await onPrepare([editing ? { kind: 'update_automation', automationId: editing, automation } : { kind: 'create_automation', automation }]); setForm(false); setNotice('Planul regulii este pregătit. Verifică parametrii și confirmă-l în conversație.');
  });
  const disabled = busy || loading || !user;
  const replaceEffect = (index: number, effect: EventRule['effects'][number]) => setExtraEffects(old => old.map((row, position) => position === index ? effect : row));
  const effectCount = Number(Boolean(description.trim())) + Number(Boolean(title.trim())) + extraEffects.length;
  return <section className="space-y-3 rounded-3xl border bg-background p-5"><h2 className="font-semibold">Automatizări și reguli CRM</h2><p className="text-xs text-muted-foreground">Rulează cu drepturile tale. Oprește la termen sau la limita de evenimente.</p><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" disabled={disabled} onClick={() => void load()}>Vezi automatizările</Button><Button size="sm" variant="outline" disabled={disabled} onClick={() => edit()}>Regulă nouă</Button><Button size="sm" variant="outline" disabled={disabled} onClick={() => { setForm(false); setNotice(''); setDefinitionEditor({}); }}>Automatizare nouă</Button></div>
    {error && <p role="alert" className="text-sm text-destructive">{error}</p>}{notice && <p role="status" className="text-xs text-muted-foreground">{notice}</p>}
    {definitionEditor && <AutomationDefinitionEditor key={definitionEditor.row?.id || "new"} row={definitionEditor.row} disabled={disabled} onPrepare={async actions => { await onPrepare(actions); setNotice("Planul automatizării este pregătit pentru confirmare."); }} onClose={() => setDefinitionEditor(null)} />}
    {form && <form className="space-y-3 rounded-xl border p-3" onSubmit={e => { e.preventDefault(); void save(); }}>
      <label className="block text-sm">Modul<select className={selectClass} value={resource} onChange={e => setResource(e.target.value as EventRule['trigger']['resource'])}>{Object.entries(resources).map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label>
      <label className="block text-sm">Eveniment<select className={selectClass} value={change} onChange={e => setChange(e.target.value as 'created' | 'updated')}><option value="created">Înregistrare nouă</option><option value="updated">Înregistrare modificată</option></select></label>
      <label className="block text-sm">Câmp urmărit<select className={selectClass} value={field} onChange={e => setField(e.target.value)}><option value="">Orice modificare</option>{['status', 'stage', 'agentId', 'collaborationStatus', 'contactOutcome', 'viewingDate', 'price', 'budget', 'financingType'].map(value => <option key={value} value={value}>{({ status: 'Status', stage: 'Etapă', agentId: 'Agent', collaborationStatus: 'Colaborare', contactOutcome: 'Rezultat prospectare', viewingDate: 'Data vizionării', price: 'Preț', budget: 'Buget', financingType: 'Finanțare' } as Record<string, string>)[value]}</option>)}</select></label>
      <fieldset className="flex flex-wrap gap-2 text-xs"><legend>Alte câmpuri urmărite</legend>{trackedFields.filter(value => value !== field).map(value => <label key={value}><input type="checkbox" checked={additionalFields.includes(value)} onChange={e => setAdditionalFields(old => e.target.checked ? [...old, value] : old.filter(item => item !== value))} /> {fieldNames[value]}</label>)}</fieldset>
      <label className="block text-sm">Status anterior (opțional)<Input value={from} onChange={e => setFrom(e.target.value)} maxLength={100} /></label><label className="block text-sm">Status nou (opțional)<Input value={to} onChange={e => setTo(e.target.value)} maxLength={100} /></label><label className="block text-sm">Doar înregistrarea cu ID (opțional)<Input value={recordId} onChange={e => setRecordId(e.target.value)} maxLength={180} /></label>
      <label className="block text-sm">Sarcină de creat (gol = fără sarcină)<Input value={description} onChange={e => setDescription(e.target.value)} maxLength={2000} /></label><label className="block text-sm">Termen după eveniment, minute<Input type="number" min="0" max="43200" value={delay} onChange={e => setDelay(e.target.value)} required /></label><label className="block text-sm">Notificare proprie (gol = fără notificare)<Input value={title} onChange={e => setTitle(e.target.value)} maxLength={200} /></label>
      <label className="block text-sm">Agent responsabil<select className={selectClass} value={taskAgent} onChange={e => setTaskAgent(e.target.value)}><option value="">Agentul care creează regula</option>{taskAgent && !agents.some(agent => agent.id === taskAgent) && <option value={taskAgent}>Agent configurat</option>}{agents.map(agent => <option key={agent.id} value={agent.id}>{agent.name || agent.email || 'Agent'}</option>)}</select></label><label className="block text-sm">Conținut notificare<Input value={notifyBody} onChange={e => setNotifyBody(e.target.value)} maxLength={2000} /></label>
      <label className="block text-sm">Prima verificare (ora dispozitivului)<Input type="datetime-local" value={firstRunValue} onChange={e => setFirstRunValue(e.target.value)} required /></label><label className="block text-sm">Oprește regula după (opțional, ora dispozitivului)<Input type="datetime-local" value={stopValue} onChange={e => setStopValue(e.target.value)} /></label>
      {extraEffects.map((effect, index) => <fieldset key={index} className="space-y-2 rounded-xl border p-3"><legend>Acțiune suplimentară {index + 1}</legend>{effect.kind === 'create_task' ? <><label className="block text-sm">Descriere sarcină suplimentară {index + 1}<Input value={effect.description} onChange={e => replaceEffect(index, { ...effect, description: e.target.value })} maxLength={2000} required /></label><label className="block text-sm">Termen sarcină suplimentară {index + 1}, minute<Input type="number" min="0" max="43200" value={effect.dueAfterMinutes} onChange={e => replaceEffect(index, { ...effect, dueAfterMinutes: Number(e.target.value) })} required /></label><label className="block text-sm">Agent sarcină suplimentară {index + 1}<select className={selectClass} value={effect.agentId || ''} onChange={e => { const { agentId: _, ...rest } = effect; replaceEffect(index, { ...rest, ...(e.target.value ? { agentId: e.target.value } : {}) }); }}><option value="">Agentul care creează regula</option>{effect.agentId && !agents.some(agent => agent.id === effect.agentId) && <option value={effect.agentId}>Agent configurat</option>}{agents.map(agent => <option key={agent.id} value={agent.id}>{agent.name || agent.email || 'Agent'}</option>)}</select></label></> : <><label className="block text-sm">Titlu notificare suplimentară {index + 1}<Input value={effect.title} onChange={e => replaceEffect(index, { ...effect, title: e.target.value })} maxLength={200} required /></label><label className="block text-sm">Conținut notificare suplimentară {index + 1}<Input value={effect.body} onChange={e => replaceEffect(index, { ...effect, body: e.target.value })} maxLength={2000} /></label></>}<Button type="button" variant="ghost" size="sm" onClick={() => setExtraEffects(old => old.filter((_, position) => position !== index))}>Elimină acțiunea suplimentară {index + 1}</Button></fieldset>)}
      <div className="flex gap-2"><Button type="button" size="sm" variant="outline" disabled={disabled || effectCount >= 5} onClick={() => setExtraEffects(old => [...old, { kind: 'create_task', description: '', dueAfterMinutes: 60 }])}>Adaugă sarcină suplimentară</Button><Button type="button" size="sm" variant="outline" disabled={disabled || effectCount >= 5} onClick={() => setExtraEffects(old => [...old, { kind: 'notify', title: '', body: '' }])}>Adaugă notificare suplimentară</Button></div>
      <label className="block text-sm">Interval verificare, minute<Input type="number" min="30" max="43200" value={interval} onChange={e => setInterval(e.target.value)} required /></label><label className="block text-sm">Maximum verificări<Input type="number" min="1" max="365" value={runs} onChange={e => setRuns(e.target.value)} required /></label><label className="block text-sm">Maximum evenimente<Input type="number" min="1" max="1000" value={maxEvents} onChange={e => setMaxEvents(e.target.value)} required /></label><p className="text-xs text-muted-foreground">Se aplică evenimentelor viitoare. Efectele sunt sarcini și notificări; comunicările externe au flux separat.</p><div className="flex gap-2"><Button size="sm" type="submit" disabled={disabled || !effectCount}>Pregătește regula</Button><Button size="sm" type="button" variant="ghost" onClick={() => setForm(false)}>Închide</Button></div>
    </form>}
    {opened && <div className="max-h-96 space-y-2 overflow-auto">{rows.map(row => <article key={row.id} className="space-y-2 rounded-xl border p-3 text-sm"><strong>{names[row.automation?.type] || 'Automatizare'}</strong><p>{row.status} · {row.runCount || 0} verificări{row.automation?.maxRuns ? ' / ' + row.automation.maxRuns : ''}</p>{row.automation?.trigger && <p>{resources[row.automation.trigger.resource as keyof typeof resources]} · {row.automation.trigger.statusTo || 'evenimente configurate'}</p>}{row.error && <p className="text-destructive">{row.error}</p>}{row.deliveryEvidence && <p>{deliveryNames[row.deliveryEvidence.status] || 'Livrare neconfirmată'} · {row.deliveryEvidence.note}</p>}<div className="flex flex-wrap gap-1">{['active', 'paused'].includes(row.status) && <Button size="sm" variant="outline" disabled={disabled} onClick={() => void prepare({ kind: 'update_automation', automationId: row.id, status: row.status === 'active' ? 'paused' : 'active' })}>{row.status === 'active' ? 'Pauză' : 'Reia'}</Button>}{row.automation && ['active', 'paused'].includes(row.status) && <Button size="sm" variant="outline" disabled={disabled} onClick={() => { if (row.automation.type === 'event_rule') edit(row); else { setForm(false); setNotice(''); setDefinitionEditor({ row }); } }}>Editează</Button>}<Button size="sm" variant="ghost" disabled={disabled} onClick={() => void loadHistory(row.id)}>Istoric</Button></div></article>)}{!rows.length && <p className="text-sm text-muted-foreground">Nu există automatizări în acest segment.</p>}{cursor && <Button size="sm" variant="outline" disabled={disabled} onClick={() => void load(true)}>Încarcă următoarele</Button>}</div>}
    {historyTarget && <div className="space-y-2 rounded-xl border p-3"><strong className="text-sm">Istoric execuții</strong>{history.map(row => <p key={row.id} className="text-xs">{row.occurredAt} · {row.action} · {row.status || ''}{row.error ? ' · ' + row.error : ''}{row.deliveryEvidence?.note ? ' · ' + (deliveryNames[row.deliveryEvidence.status] || 'Livrare neconfirmată') + ': ' + row.deliveryEvidence.note : ''}{row.result?.reasonCode === 'quiet_hours' ? ' · Raport amânat pentru respectarea intervalului de liniște.' : ''}{row.result?.reasonCode === 'missed_local_day' ? ' · Zi ratată; brief-ul nu a fost trimis.' : ''}{Array.isArray(row.result?.notificationResults) && row.result.notificationResults.some((result: Row) => result.reasonCode === 'cooldown') ? ' · Alertele repetitive au fost omise în perioada de pauză.' : ''}{Array.isArray(row.result?.notificationResults) && row.result.notificationResults.some((result: Row) => result.reasonCode === 'notification_cap') ? ' · Unele alerte au fost omise: plafonul comun de 10 alerte în 24 de ore a fost atins.' : ''}{row.result?.handled != null ? ' · ' + row.result.handled + ' evenimente executate' : ''}</p>)}{!history.length && <p className="text-xs text-muted-foreground">Nicio execuție în segmentul curent.</p>}{historyCursor && <Button size="sm" variant="outline" disabled={disabled} onClick={() => void loadHistory(historyTarget, true)}>Istoric anterior</Button>}</div>}
  </section>;
}


