import { describe, expect, it } from 'vitest';
import { analysisSchema, datetimeSchema } from '../deterministic-contracts';
import { analyzeRows, resolveDatetime } from '../deterministic';
describe('server arithmetic, filters and dates', () => {
  it('calculates tomorrow in Bucharest, including a UTC/local date boundary', () => { const result = resolveDatetime(datetimeSchema.parse({ dayOffset: 1, time: '14:00' }), new Date('2026-10-03T22:00:00Z')); expect(result.iso).toBe('2026-10-05T11:00:00.000Z'); });
  it('normalizes explicit local time without model arithmetic', () => { expect(resolveDatetime(datetimeSchema.parse({ date: '2026-10-10', time: '14:00' })).iso).toBe('2026-10-10T11:00:00.000Z'); });
  it('rejects nonexistent and ambiguous daylight saving times', () => { expect(() => resolveDatetime(datetimeSchema.parse({ date: '2026-03-29', time: '03:30' }))).toThrow('nu există'); expect(() => resolveDatetime(datetimeSchema.parse({ date: '2026-10-25', time: '03:30' }))).toThrow('ambiguă'); expect(resolveDatetime(datetimeSchema.parse({ date: '2026-10-25', time: '03:30', utcOffsetMinutes: 120 })).iso).toBe('2026-10-25T01:30:00.000Z'); });
  it('rejects invalid calendar dates and unspecified or conflicting date inputs', () => { expect(() => resolveDatetime(datetimeSchema.parse({ date: '2026-02-30', time: '12:00' }))).toThrow(); expect(() => datetimeSchema.parse({ time: '12:00' })).toThrow(); expect(() => datetimeSchema.parse({ date: '2026-10-10', dayOffset: 1, time: '12:00' })).toThrow(); });
  it('calculates numeric totals on exactly the filtered authorized set', () => { const input = analysisSchema.parse({ resource: 'properties', ids: ['1', '2', '3'], filters: [{ field: 'location', operator: 'contains', value: 'Titan' }], sort: { field: 'price', direction: 'asc' }, numericField: 'price' }); const report = analyzeRows([{ id: '1', location: 'Titan', price: 130000 }, { id: '2', location: 'Titan', price: 110000 }, { id: '3', location: 'Pipera', price: 200000 }], input); expect(report.rows.map(row => row.id)).toEqual(['2','1']); expect(report.statistics).toMatchObject({ count: 2, sum: 240000, average: 120000, min: 110000, max: 130000 }); expect(report.scope).toBe('selected_authorized_records'); });
  it('filters dates as instants and rejects credential fields', () => { const input = analysisSchema.parse({ resource: 'tasks', ids: ['1'], filters: [{ field: 'dueDate', operator: 'eq', value: '2026-10-10T14:00:00+03:00' }] }); expect(analyzeRows([{ id: '1', dueDate: '2026-10-10T11:00:00Z' }], input).rows).toHaveLength(1); expect(() => analysisSchema.parse({ resource: 'agency', ids: ['a'], numericField: 'accessToken' })).toThrow(); });
});
