'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { Facebook, Instagram, LayoutDashboard, PenLine, CalendarDays, RefreshCw, MessageCircle } from 'lucide-react';
import { MetaIcon } from '@/components/icons/MetaIcon';
import '@/components/marketing/tiktok-ads/tiktok-workspace.css';
import './meta-workspace.css';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import type { Connection } from '@/lib/communications/model';
import { useCommunications } from './useCommunications';
type FBSDK = { init: (config: Record<string, unknown>) => void; login: (callback: (response: { authResponse?: { code?: string } }) => void, options: Record<string, unknown>) => void };
type Dashboard = { connections: Connection[]; budgets: Array<{ id: string; currency: string; limitMicros?: number; spentMicros?: number; reservedMicros?: number }>; config: { appId: string; version: string; whatsappConfigId: string; whatsappReady: boolean; searchReady: boolean }; admin: boolean };
const field = 'w-full rounded-lg border border-slate-200 bg-white p-2 text-sm';
const capabilityLabels: Record<string, string> = { publish: 'Publicare', receive: 'Primire mesaje', send: 'Trimitere mesaje', nativeSync: 'Sincronizare externă', templates: 'Șabloane', comments: 'Comentarii', insights: 'Statistici' };
const statusLabels: Record<string, string> = { active: 'Activ', configuration_required: 'Necesită configurare', reconnect_required: 'Necesită reconectare', unavailable: 'Indisponibil' };
export default function MarketingWorkspace({ whatsapp = false }: { whatsapp?: boolean }) {
  const api = useCommunications(); const [data, setData] = useState<Dashboard | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState('');
  const [tab, setTab] = useState('accounts'); const [pages, setPages] = useState<Array<{ id: string; name: string }>>([]);
  const [properties, setProperties] = useState<Array<{ id: string; title: string }>>([]); const [posts, setPosts] = useState<Array<{ id: string; text: string; status: string; scheduledAt: string; destinations: Record<string, { status: string; externalId?: string; error?: string }> }>>([]);
  const [features, setFeatures] = useState(['publish', 'messaging']); const [targets, setTargets] = useState<string[]>([]);
  const [property, setProperty] = useState(''); const [text, setText] = useState(''); const [scheduled, setScheduled] = useState('');
  const [budget, setBudget] = useState(''); const [currency, setCurrency] = useState('EUR');
  const [templates, setTemplates] = useState<Array<{ name: string; language: string; category: string; status: string }>>([]);
  const [mode, setMode] = useState('coexistence');
  const [pin, setPin] = useState('');
  const [interaction, setInteraction] = useState<{ postId: string; connectionId: string; comments: Array<{ id: string; text?: string; message?: string; username?: string; from?: { name?: string } }> } | null>(null);
  const [publicReply, setPublicReply] = useState('');
  const [metrics, setMetrics] = useState<{ likes: number | null; comments: number | null } | null>(null);
  const signup = useRef<{ wabaId?: string; phoneNumberId?: string; code?: string; active?: boolean }>({});
  const load = useCallback(async () => {
    const value = await api('dashboard'); setData(value);
    if (!whatsapp && value.admin) { const [assets, props, history] = await Promise.all([api('assets'), api('properties'), api('posts')]); setPages(assets.pages); setProperties(props.properties); setPosts(history.posts); }
  }, [api, whatsapp]);
  useEffect(() => { load().catch(e => setError(e.message)); const params = new URLSearchParams(window.location.search); if (params.get('error')) setError(params.get('error')!); if (params.get('propertyId')) setProperty(params.get('propertyId')!); }, [load]);
  async function act(fn: () => Promise<unknown>) { setBusy(true); setError(''); setNotice(''); try { await fn(); } catch (e) { setError(e instanceof Error ? e.message : 'Operația a eșuat.'); } finally { setBusy(false); } }
  const complete = useCallback(async () => {
    const s = signup.current;
    if (!s.active || !s.code || !s.wabaId || !s.phoneNumberId) return;
    signup.current = {};
    try { await api('whatsapp', 'POST', { code: s.code, wabaId: s.wabaId, phoneNumberId: s.phoneNumberId, mode, ...(mode === 'cloud' ? { pin } : {}) }); setPin(''); setNotice('Numărul a fost conectat. Trimite un mesaj de test pentru verificarea recepției.'); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Conectarea a eșuat.'); }
  }, [api, load, mode, pin]);
  useEffect(() => {
    const listener = (event: MessageEvent) => {
      if (!['https://www.facebook.com', 'https://web.facebook.com'].includes(event.origin) || !signup.current.active) return;
      try {
        const payload = typeof event.data === 'string' ? JSON.parse(event.data) : event.data;
        if (payload.type !== 'WA_EMBEDDED_SIGNUP') return;
        if (payload.event === 'CANCEL' || payload.event === 'ERROR') { signup.current = {}; setError('Conectarea WhatsApp nu a fost finalizată.'); return; }
        if (payload.data?.waba_id && payload.data?.phone_number_id) { signup.current.wabaId = payload.data.waba_id; signup.current.phoneNumberId = payload.data.phone_number_id; void complete(); }
      } catch { /* Ignore messages that are not signup payloads. */ }
    };
    window.addEventListener('message', listener); return () => window.removeEventListener('message', listener);
  }, [complete]);
  async function connectWhatsApp() {
    if (!data?.config.whatsappReady) throw new Error('Configurarea WhatsApp și plata directă nu sunt activate pe server.');
    if (mode === 'cloud' && !/^\d{6}$/.test(pin)) throw new Error('Setează un PIN din 6 cifre pentru numărul dedicat.');
    const win = window as unknown as { FB?: FBSDK };
    if (!win.FB) await new Promise<void>((resolve, reject) => { const script = document.createElement('script'); script.src = 'https://connect.facebook.net/en_US/sdk.js'; script.onload = () => resolve(); script.onerror = () => reject(new Error('SDK-ul Meta nu a putut fi încărcat.')); document.head.appendChild(script); });
    win.FB!.init({ appId: data.config.appId, version: data.config.version, xfbml: false });
    signup.current = { active: true };
    win.FB!.login(response => { if (response.authResponse?.code) { signup.current.code = response.authResponse.code; void complete(); } else { signup.current = {}; setError('Conectarea a fost anulată.'); } }, { config_id: data.config.whatsappConfigId, response_type: 'code', override_default_response_type: true, extras: { sessionInfoVersion: '3', ...(mode === 'coexistence' ? { featureType: 'whatsapp_business_app_onboarding' } : {}) } });
  }
  const connections = data?.connections.filter(c => whatsapp ? c.channel === 'whatsapp' : ['messenger', 'instagram'].includes(c.channel)) || [];
  const tabs = whatsapp ? [['accounts', 'Numere'], ['templates', 'Șabloane'], ['budget', 'Consum']] : [['accounts', 'Conturi'], ['compose', 'Creează postare'], ['history', 'Calendar și istoric']];
  return <div className={whatsapp ? "min-h-screen bg-slate-50 p-4 text-slate-900 lg:p-7" : "tt-design tt-workspace mi-workspace"}>
    {whatsapp ? <header className="mb-6 rounded-2xl bg-slate-900 p-6 text-white"><p className="text-xs uppercase tracking-widest text-emerald-300">Marketing · Comunicare</p><h1 className="mt-2 text-3xl font-semibold">WhatsApp</h1><p className="mt-2 max-w-2xl text-slate-300">Conectează numărul agenției, gestionează șabloanele și controlează consumul. Conversațiile sunt în Inbox.</p><Button className="mt-4" variant="secondary" asChild><Link href="/inbox">Deschide Inbox</Link></Button></header> : <>
      <header className="tt-hero mi-hero"><div className="mi-hero-copy"><div className="tt-hero-kicker"><MetaIcon className="mi-hero-logo" /><span className="tt-eyebrow">SPAȚIUL TĂU DE PUBLICARE</span></div><h1>Facebook <em>+ Instagram</em></h1><p className="mi-hero-lead">Proprietățile tale, <strong>mai aproape de oamenii potriviți.</strong></p><p>Pregătește postări, urmărește conversațiile și administrează ambele conturi într-un singur loc.</p><div className="tt-hero-actions"><Button className="tt-button tt-button--default" onClick={() => setTab('compose')}><PenLine size={16} />Creează postare</Button><Button className="tt-button tt-button--outline" variant="outline" asChild><Link href="/inbox"><MessageCircle size={16} />Deschide Inbox</Link></Button></div></div><div className="mi-hero-art" aria-hidden="true"><div className="mi-orbit mi-orbit--one" /><div className="mi-orbit mi-orbit--two" /><div className="mi-social-card mi-social-card--facebook"><span className="mi-social-icon mi-social-icon--facebook"><Facebook /></span><span className="mi-social-lines"><i /><i /><i /></span><span className="mi-social-photo"><span /><span /></span></div><div className="mi-social-card mi-social-card--instagram"><span className="mi-social-icon mi-social-icon--instagram"><Instagram /></span><span className="mi-social-lines"><i /><i /></span><span className="mi-social-photo mi-social-photo--warm"><span /><span /></span></div><span className="mi-hero-spark mi-hero-spark--one">✦</span><span className="mi-hero-spark mi-hero-spark--two">✦</span></div></header>
      <div className="tt-context mi-context"><span className="tt-context-avatar"><MetaIcon /></span><div className="mi-context-label"><span>CONTURI CONECTATE</span><strong>{connections.length ? `${connections.length} conturi` : 'Niciun cont'}</strong></div><p className="tt-context-meta">{connections.filter(c => c.channel === 'messenger').length} Facebook · {connections.filter(c => c.channel === 'instagram').length} Instagram</p><span className={`mi-context-status ${connections.length ? 'mi-context-status--active' : ''}`}><span />{connections.length ? 'Conectat la Meta' : 'Conectează un cont'}</span><Button className="tt-button tt-button--outline" variant="outline" disabled={busy} onClick={() => act(load)}><RefreshCw size={15} />Actualizează</Button></div>
    </>}
    {error && <p role="alert" className="mb-4 rounded-lg bg-amber-50 p-3 text-amber-900">{error}</p>}{notice && <p role="status" className="mb-4 rounded-lg bg-emerald-50 p-3">{notice}</p>}
    <nav aria-label="Sectiuni marketing" className={whatsapp ? "mb-5 flex flex-wrap gap-2" : "tt-nav mi-nav"}>{tabs.map(([id,label]) => <Button key={id} className={whatsapp ? undefined : "tt-button"} variant={tab === id ? "default" : whatsapp ? "outline" : "ghost"} aria-current={tab === id ? "page" : undefined} onClick={() => setTab(id)}>{!whatsapp && (id === "accounts" ? <LayoutDashboard size={16} /> : id === "compose" ? <PenLine size={16} /> : <CalendarDays size={16} />)}{label}</Button>)}</nav>
    {tab === 'accounts' && <div className={whatsapp ? "space-y-4" : "mi-account-layout"}><section className={whatsapp ? "rounded-xl border bg-white p-5" : "tt-panel mi-connect-panel"}><h2 className="mb-3 text-lg font-semibold">Conectează contul agenției</h2>{whatsapp ? <><select className={field} value={mode} onChange={e => setMode(e.target.value)}><option value="coexistence">Număr existent în WhatsApp Business App</option><option value="cloud">Număr dedicat Cloud API</option></select>{mode === 'cloud' && <Input className="mt-3" type="password" inputMode="numeric" maxLength={6} value={pin} onChange={e => setPin(e.target.value)} aria-label="PIN de securitate din 6 cifre" placeholder="Setează PIN-ul din 6 cifre pentru numărul dedicat"/>}<p className="my-3 text-sm text-slate-500">Pentru numărul existent folosim Coexistence. Dacă nu este eligibil, poți conecta un număr dedicat; contul existent nu este migrat automat.</p><Button disabled={busy || !data?.admin || !data?.config.whatsappReady} onClick={() => act(connectWhatsApp)}>Conectează WhatsApp</Button>{!data?.config.whatsappReady && <p className="mt-2 text-sm text-amber-800">Necesită configurarea Embedded Signup și a plății directe către Meta.</p>}</> : <><div className="mi-feature-list">{[['publish','Publicare'],['messaging','Mesagerie'],['comments','Comentarii'],['insights','Statistici']].map(([id,label]) => <label key={id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={features.includes(id)} onChange={e => setFeatures(prev => e.target.checked ? [...prev,id] : prev.filter(f => f !== id))}/>{label}</label>)}</div><Button disabled={busy || !data?.admin || !features.length} onClick={() => act(async () => { const value = await api('connect', 'POST', { features }); window.location.assign(value.authorizationUrl); })}>Conectează Facebook + Instagram</Button><div className="mi-page-list">{pages.map(page => <div key={page.id} className="flex items-center justify-between gap-3 rounded-lg border p-3"><span>{page.name}</span><Button variant="outline" disabled={busy} onClick={() => act(async () => { await api('assets','POST',{pageId:page.id}); await load(); })}>Selectează pagina</Button></div>)}</div></>}</section>
      {!connections.length && <div className="tt-panel mi-empty">Nu există conturi conectate.</div>}{connections.map(c => <section key={c.id} className={whatsapp ? "rounded-xl border bg-white p-5" : "tt-panel mi-connection"}><div className="flex items-center justify-between mi-connection-header"><div className="mi-connection-identity"><span className={"mi-account-icon mi-account-icon--" + c.channel}>{c.channel === "instagram" ? <Instagram size={22} /> : <Facebook size={22} />}</span><div><h3 className="font-semibold">{c.name}</h3><p className="text-xs text-slate-500">{c.channel} · {c.status === 'connected' ? 'Conectat' : 'Deconectat'}{c.lastSyncAt ? ` · Sincronizat ${new Date(c.lastSyncAt).toLocaleString('ro-RO')}` : ''}</p></div></div>{data?.admin && c.status === 'connected' && <Button variant="outline" disabled={busy} onClick={() => act(async () => { await api(`connections/${c.id}`, 'DELETE', {}); await load(); })}>Deconectează</Button>}</div><div className={whatsapp ? "mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3" : "mi-capability-grid"}>{Object.entries(c.capabilities).map(([key,value]) => <div key={key} className="rounded-lg bg-slate-50 p-3"><strong className="text-sm">{capabilityLabels[key] || key}</strong><p className={`text-sm ${value.status === 'active' ? 'text-emerald-700' : 'text-amber-800'}`}>{statusLabels[value.status]}</p><p className="mt-1 text-xs text-slate-500">{value.reason}</p></div>)}</div></section>)}</div>}
    {tab === 'compose' && <section className="tt-panel mi-compose"><h2 className="text-lg font-semibold">O postare nouă</h2><select className={field} value={property} onChange={e => setProperty(e.target.value)} aria-label="Proprietate"><option value="">Alege proprietatea</option>{properties.map(p => <option key={p.id} value={p.id}>{p.title}</option>)}</select><Textarea rows={7} maxLength={2200} placeholder="Textul postării" value={text} onChange={e => setText(e.target.value)}/><p className="text-xs text-slate-500">Se folosesc primele 10 fotografii ale proprietății. Proprietatea și prețul sunt reverificate înainte de publicare.</p><div className="flex flex-wrap gap-3">{connections.filter(c => c.status === 'connected' && c.capabilities.publish?.status === 'active').map(c => <label key={c.id} className="flex items-center gap-2"><input type="checkbox" checked={targets.includes(c.id)} onChange={e => setTargets(prev => e.target.checked ? [...prev,c.id] : prev.filter(id => id !== c.id))}/>{c.name} · {c.channel === 'messenger' ? 'Facebook' : 'Instagram'}</label>)}</div><label className="block text-sm">Programare opțională (ora dispozitivului)<Input type="datetime-local" value={scheduled} onChange={e => setScheduled(e.target.value)}/></label><div className="flex gap-2">{[true,false].map(draft => <Button key={String(draft)} disabled={busy || !data?.admin || !property || !text || !targets.length} variant={draft ? 'outline' : 'default'} onClick={() => act(async () => { await api('posts','POST',{ requestId: crypto.randomUUID(), connectionIds: targets, propertyId: property, text, draft, ...(scheduled ? { scheduledAt: new Date(scheduled).toISOString() } : {}) }); setNotice(draft ? 'Draft salvat.' : 'Postarea a fost pusă în coada de publicare.'); await load(); setTab('history'); })}>{draft ? 'Salvează draft' : scheduled ? 'Programează' : 'Publică'}</Button>)}</div></section>}
    {tab === 'history' && <div className="space-y-3">{!posts.length && <p>Nu există postări create.</p>}{posts.map(p => <article key={p.id} className="tt-panel mi-post"><p className="whitespace-pre-wrap">{p.text}</p><p className="my-2 text-sm text-slate-500">{new Date(p.scheduledAt).toLocaleString('ro-RO')} · {p.status}</p>{Object.entries(p.destinations).map(([id,d]) => <p key={id} className="text-sm">{connections.find(c => c.id === id)?.name || id} · {d.status}{d.externalId ? ` · ${d.externalId}` : ''}{d.error ? ` · ${d.error}` : ''}</p>)}{p.status === 'draft' && <Button className="mt-3 mr-2" disabled={busy} onClick={() => act(async () => { await api(`posts/${p.id}/publish`, 'POST', {}); await load(); })}>Publică draftul</Button>}{['draft','queued'].includes(p.status) && <Button className="mt-3" variant="outline" onClick={() => act(async () => { await api(`posts/${p.id}`, 'DELETE', {}); await load(); })}>Anulează</Button>}</article>)}</div>}
    {tab === 'history' && <section className="tt-panel mi-interactions"><h2 className="font-semibold">Comentarii și interacțiuni</h2>{posts.flatMap(p => Object.entries(p.destinations).filter(([,d]) => d.status === 'published').map(([id]) => <div key={`${p.id}-${id}`} className="flex flex-wrap gap-2 border-t pt-3"><span className="max-w-xs truncate text-sm">{p.text}</span><Button variant="outline" disabled={busy} onClick={() => act(async () => { const result = await api(`posts/${p.id}/comments?connectionId=${id}`); setInteraction({postId:p.id,connectionId:id,comments:result.data || []}); })}>Comentarii</Button><Button variant="outline" disabled={busy} onClick={() => act(async () => { const result = await api(`posts/${p.id}/insights?connectionId=${id}`); setMetrics({likes:result.like_count ?? result.likes?.summary?.total_count ?? null,comments:result.comments_count ?? result.comments?.summary?.total_count ?? null}); })}>Interacțiuni</Button></div>))}{metrics && <p>Aprecieri: {metrics.likes ?? 'Indisponibil'} · Comentarii: {metrics.comments ?? 'Indisponibil'}</p>}{interaction && <div className="space-y-3">{interaction.comments.map(c => <article key={c.id} className="rounded-lg bg-slate-50 p-3"><strong className="text-sm">{c.username || c.from?.name || 'Utilizator'}</strong><p>{c.text || c.message}</p></article>)}<Textarea value={publicReply} onChange={e => setPublicReply(e.target.value)} placeholder="Comentariu public la postare"/><Button disabled={busy || !publicReply.trim()} onClick={() => act(async () => { await api(`posts/${interaction.postId}/comments`, 'POST', {connectionId:interaction.connectionId,text:publicReply}); setPublicReply(''); const result = await api(`posts/${interaction.postId}/comments?connectionId=${interaction.connectionId}`); setInteraction({...interaction,comments:result.data || []}); })}>Publică un comentariu</Button></div>}</section>}
    {tab === 'templates' && <section className="rounded-xl border bg-white p-5"><h2 className="mb-3 text-lg font-semibold">Șabloane aprobate în Meta</h2><div className="mb-4 flex gap-2">{connections.filter(c => c.status === 'connected').map(c => <Button key={c.id} variant="outline" disabled={busy} onClick={() => act(async () => { const value = await api(`templates/${c.id}`); setTemplates(value.data || []); })}>{c.name}</Button>)}</div>{templates.map(t => <div key={`${t.name}-${t.language}`} className="border-t py-3"><strong>{t.name}</strong><p className="text-sm text-slate-500">{t.language} · {t.category} · {t.status}</p></div>)}<a className="mt-4 block text-sm text-emerald-700" href="https://business.facebook.com/wa/manage/message-templates/" target="_blank" rel="noreferrer">Gestionează șabloanele în Meta</a></section>}
    {tab === 'budget' && <section className="max-w-3xl space-y-4 rounded-xl border bg-white p-5"><h2 className="text-lg font-semibold">Consum și plafon lunar</h2><p className="text-sm text-slate-500">Meta facturează direct agenției. Plafonul controlează trimiterile din ImoDeus; factura poate include și trafic din alte aplicații. Sumele sunt estimări, nu facturi.</p>{data?.budgets.map(b => <div key={b.id} className="rounded-lg bg-slate-50 p-3"><strong>{b.id}</strong><p className="text-sm">Plafon: {((b.limitMicros || 0)/1e6).toFixed(2)} · Consumat estimat: {((b.spentMicros || 0)/1e6).toFixed(4)} · Rezervat: {((b.reservedMicros || 0)/1e6).toFixed(4)} {b.currency}</p>{(b.limitMicros || 0) > 0 && ((b.spentMicros || 0)+(b.reservedMicros || 0))/(b.limitMicros || 1) >= .8 && <p className="text-sm text-amber-700">Plafonul este aproape epuizat.</p>}</div>)}<div className="flex gap-2"><Input aria-label="Plafon lunar" type="number" min="0" step="0.01" value={budget} onChange={e => setBudget(e.target.value)} placeholder="Plafon lunar"/><select aria-label="Monedă" className={field} value={currency} onChange={e => setCurrency(e.target.value)}><option>EUR</option><option>RON</option><option>USD</option></select><Button disabled={busy || !data?.admin || budget === ''} onClick={() => act(async () => { await api('budget', 'POST', {limitMicros: Math.round(Number(budget)*1e6),currency}); await load(); setNotice('Plafonul lunii curente a fost salvat.'); })}>Salvează</Button></div><p className="text-xs text-slate-500">Recepția rămâne activă când plafonul este epuizat. Un tarif neconfigurat blochează trimiterile potențial taxabile.</p></section>}
  </div>;
}


