'use client';
import { useState, type ReactNode } from 'react';
import Link from 'next/link';
import { ArrowUpRight, ArrowRight, MessageCircle, Phone, FileText, Wallet, Plus, RefreshCw, Check, ShieldCheck, Inbox, Radio, Send, Settings2, X } from 'lucide-react';
import type { Connection } from '@/lib/communications/model';
import WhatsAppTemplates from './WhatsAppTemplates';
import WhatsAppConnectionGuide from './WhatsAppConnectionGuide';
import './whatsapp-studio.css';
import './whatsapp-studio-v2.css';

type Budget = { id: string; currency: string; limitMicros?: number; spentMicros?: number; reservedMicros?: number };
type Props = { connections: Connection[]; budgets: Budget[]; loading: boolean; admin: boolean; allowed: boolean; busy: boolean; error: string; notice: string; onboarding: ReactNode; refresh: () => void; disconnect: (id: string) => void; saveBudget: (amount: number, currency: string) => Promise<void> };
const labels: Record<string, string> = { active: 'Activ', configuration_required: 'De configurat', reconnect_required: 'Reconectare necesară', unavailable: 'Indisponibil' };
export default function WhatsAppStudio(p: Props) {
 const [tab, setTab] = useState('overview'); const [connecting, setConnecting] = useState(false);
 const [amount, setAmount] = useState(''); const [currency, setCurrency] = useState('EUR');
 const active = p.connections.filter(c => c.status === 'connected');
 const receiving = active.filter(c => c.capabilities.receive?.status === 'active').length;
 const [disconnectId, setDisconnectId] = useState<string | null>(null);
 return <div className="wa-studio">
  <header className="wa-hero">
   <div className="wa-hero-copy"><div className="wa-eyebrow"><MessageCircle size={17}/> WHATSAPP BUSINESS</div><h1>WhatsApp <span>Studio.</span></h1><p>Conversații care deschid uși.<br/>Un singur studio pentru fiecare conexiune.</p><div className="wa-actions"><Link className="wa-btn wa-primary" href="/inbox"><Inbox size={17}/> Deschide Inbox <ArrowUpRight size={17}/></Link><button className="wa-btn" onClick={() => setTab('templates')}><FileText size={17}/> Explorează șabloanele</button></div></div>
   <div className="wa-hero-visual" aria-hidden="true"><div className="wa-composer-art"><div className="wa-art-header"><span className="wa-art-avatar"><MessageCircle size={23}/></span><div><strong>Următoarea conversație</strong><small>Poate fi începutul unei colaborări.</small></div><span>WHATSAPP</span></div><div className="wa-bubble wa-bubble-one">Bună! Putem programa o vizionare?<span>Conversație cu agenția</span></div><div className="wa-bubble wa-bubble-two">Sigur! Găsim împreună momentul potrivit.<span><Check size={13}/><Check size={13}/></span></div></div><span className="wa-art-sticker">OAMENI. LOCURI. CONVERSAȚII.</span><span className="wa-send-art"><Send size={36} strokeWidth={1.7}/></span></div>
  </header>
  {p.error && <div className="wa-alert" role="alert">{p.error}</div>}{p.notice && <div className="wa-alert wa-success" role="status">{p.notice}</div>}
  <div className="wa-metrics" aria-busy={p.loading}>{[{icon:Phone,label:'Numere conectate',value:p.loading?'—':active.length,detail:'Identitatea agenției tale'}, {icon:Radio,label:'Recepție verificată',value:p.loading?'—':`${receiving} / ${active.length}`,detail:'Numere cu mesaje primite'}, {icon:ShieldCheck,label:'Controlul trimiterilor',value:'Verificare la trimitere',detail:'Eligibilitate, tarif și plafon'}].map(m=><div className="wa-metric" key={m.label}><span className="wa-icon"><m.icon size={20}/></span><div><span>{m.label}</span><strong>{m.value}</strong><small>{m.detail}</small></div></div>)}</div>
  <div className="wa-navigation"><nav aria-label="Secțiuni WhatsApp Studio">{[{id:'overview',label:'Privire de ansamblu',icon:MessageCircle},{id:'templates',label:'Șabloane',icon:FileText},{id:'budget',label:'Consum și buget',icon:Wallet}].map(t=><button key={t.id} aria-current={tab===t.id?'page':undefined} onClick={()=>setTab(t.id)}><t.icon size={17}/>{t.label}</button>)}</nav><button className="wa-refresh" disabled={p.busy || p.loading} onClick={p.refresh}><RefreshCw size={15} className={p.busy?'animate-spin':''}/> Actualizează</button></div>
  {tab==='overview' && <div className="wa-overview"><div className="wa-main-grid wa-overview-grid"><main><div className="wa-section-heading"><div><h2>Numerele agenției</h2><p>Conexiuni, disponibilitate și următorii pași.</p></div>{p.admin && <button className="wa-btn" onClick={()=>setConnecting(v=>!v)} aria-expanded={connecting}>{connecting?<X size={16}/>:<Plus size={16}/>} {connecting?'Închide':'Conectează număr'}</button>}</div>
   {(connecting || (!p.loading && !active.length)) && <section className="wa-panel wa-onboarding"><div className="wa-panel-title"><span className="wa-icon"><Plus size={19}/></span><div><h3>Conectează agenția la WhatsApp</h3><p>Autorizează în siguranță contul prin Meta.</p></div></div>{p.onboarding}</section>}
   {p.loading && <div className="wa-panel wa-loading" role="status">Se încarcă spațiul tău WhatsApp…</div>}
   {p.connections.map(c=><article className="wa-panel wa-account" key={c.id}><div className="wa-account-heading"><span className="wa-account-avatar"><MessageCircle size={27}/></span><div><span className="wa-eyebrow">{c.mode==='coexistence'?'WHATSAPP BUSINESS APP':'NUMĂR DEDICAT'}</span><h3>{c.name}</h3><span className={'wa-pill '+(c.status==='connected'?'wa-connected':'')}>{c.status==='connected'?<Check size={12}/>:null}{c.status==='connected'?'Conectat la Meta':'Deconectat'}</span></div></div><div className="wa-capabilities">{([{key:'receive',name:'Primire mesaje',icon:Inbox},{key:'send',name:'Trimitere mesaje',icon:Send},{key:'templates',name:'Șabloane',icon:FileText}] as const).map(item=>{const state=c.capabilities[item.key];return <div key={item.key}><div className="wa-capability-title"><item.icon size={17}/><strong>{item.name}</strong></div><span className={'wa-state '+(c.status==='connected'&&state?.status==='active'?'wa-state-ok':'')}>{c.status!=='connected'?'Deconectat':state?labels[state.status]:'Neverificat'}</span><p>{state?.reason || 'Disponibilitatea nu a fost verificată încă.'}</p></div>})}</div><footer className="wa-account-footer"><span>{c.lastSyncAt?`Ultima sincronizare · ${new Date(c.lastSyncAt).toLocaleString('ro-RO')}`:'Așteptăm prima sincronizare'}{c.currency?` · ${c.currency}`:''}</span>{p.admin && c.status==='connected' && <button onClick={()=>setDisconnectId(c.id)} className="wa-text-button">Deconectează</button>}</footer>{disconnectId===c.id && <div className="wa-confirm" role="alert"><p>Deconectezi acest număr din ImoDeus? Pentru a-l utiliza din nou va trebui să îl reconectezi.</p><button className="wa-btn" disabled={p.busy} onClick={()=>{p.disconnect(c.id);setDisconnectId(null);}}>Da, deconectează</button><button className="wa-text-button" onClick={()=>setDisconnectId(null)}>Renunță</button></div>}</article>)}
  </main><aside className="wa-aside"><section className="wa-panel wa-start"><span className="wa-eyebrow">LA ÎNDEMÂNĂ</span><h2>Următorul pas,<br/>mai simplu.</h2><Link href="/inbox"><span className="wa-icon"><Inbox size={18}/></span><span><strong>Continuă conversațiile</strong><small>Mesaje și răspunsuri în Inbox</small></span><ArrowUpRight size={17}/></Link><button onClick={()=>setTab('templates')}><span className="wa-icon"><FileText size={18}/></span><span><strong>Pregătește un șablon</strong><small>Mesaje revizuite de Meta</small></span><ArrowRight size={17}/></button><button onClick={()=>setTab('budget')}><span className="wa-icon"><Wallet size={18}/></span><span><strong>Gestionează bugetul</strong><small>Plafon și consum estimat</small></span><ArrowRight size={17}/></button></section></aside></div><section className="wa-care-notice" aria-label="Comunicare cu grijă"><ShieldCheck size={24} aria-hidden="true"/><div><h3>Comunicare cu grijă.</h3><p>Inițiază conversații cu șabloane aprobate și acordul clientului. Răspunde liber în intervalul de 24 de ore de la ultimul mesaj primit și respectă solicitările de oprire.</p></div></section><WhatsAppConnectionGuide admin={p.admin} onConnect={()=>{setConnecting(true);requestAnimationFrame(()=>document.querySelector('.wa-onboarding')?.scrollIntoView({behavior:'smooth',block:'center'}));}} onTemplates={()=>setTab('templates')} onBudget={()=>setTab('budget')}/></div>}
  {tab==='templates' && <div className="wa-template-workspace"><div className="wa-section-heading"><div><h2>Mesaje pregătite pentru momentul potrivit</h2><p>Creează, previzualizează și urmărește șabloanele agenției.</p></div></div><WhatsAppTemplates connections={p.connections} allowed={p.allowed}/></div>}
  {tab==='budget' && <div className="wa-main-grid"><section className="wa-panel"><div className="wa-panel-title"><span className="wa-icon"><Wallet size={22}/></span><div><h2>Consum și plafon lunar</h2><p>Vizibilitate asupra estimărilor. Control asupra trimiterilor.</p></div></div>{!p.budgets.length && <div className="wa-empty">Nu ai încă un plafon salvat. Configurează primul buget mai jos.</div>}{p.budgets.map(b=>{const limit=b.limitMicros||0;const used=(b.spentMicros||0)+(b.reservedMicros||0);return <div className="wa-budget" key={b.id}><div><strong>{b.currency}</strong><span>{b.id.slice(0,7)}</span></div><div className="wa-budget-amount">{((b.spentMicros||0)/1e6).toFixed(2)} <small>/ {(limit/1e6).toFixed(2)} {b.currency}</small></div><div className="wa-progress" role="progressbar" aria-label={`Buget utilizat ${b.currency}`} aria-valuenow={limit?Math.min(100,Math.round(used/limit*100)):0} aria-valuemin={0} aria-valuemax={100}><span style={{width:`${limit?Math.min(100,used/limit*100):0}%`}}/></div><p>Rezervat: {((b.reservedMicros||0)/1e6).toFixed(4)} {b.currency}{limit>0&&used/limit>=.8?' · Te apropii de plafonul lunar.':''}</p></div>})}<form className="wa-budget-form" onSubmit={e=>{e.preventDefault();void p.saveBudget(Math.round(Number(amount)*1e6),currency);}}><label>Plafon lunar<input required type="number" min="0" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0,00"/></label><label>Monedă<select value={currency} onChange={e=>setCurrency(e.target.value)}><option>EUR</option><option>RON</option><option>USD</option></select></label><button className="wa-btn wa-primary" disabled={p.busy||!p.admin||!amount}>Salvează plafonul</button></form></section><aside className="wa-guide"><Settings2 size={25}/><h3>Tu setezi limita.</h3><p>Plafonul controlează trimiterile din ImoDeus. Sumele afișate sunt estimări; factura și metoda de plată se verifică în Meta.</p><p>Moneda plafonului nu modifică moneda contului WhatsApp. Recepția rămâne disponibilă când bugetul se epuizează.</p></aside></div>}
  <footer className="wa-studio-footer"><MessageCircle size={15}/> WhatsApp Studio <span>Creat pentru relații care continuă.</span></footer>
 </div>;
}
