'use client';
import { useRef, useState } from 'react';
import { FileText, Search, RefreshCw, MessageCircle, Send, Check } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import type { Connection } from '@/lib/communications/model';
import { useCommunications } from './useCommunications';
type Template = { name: string; language: string; status: string; category: string };
const statuses: Record<string,string> = { APPROVED:'Aprobat', PENDING:'În verificare', REJECTED:'Respins', PAUSED:'În pauză', DISABLED:'Dezactivat' };
export default function WhatsAppTemplates({ connections, allowed }: { connections: Connection[]; allowed: boolean }) {
 const api=useCommunications();
 const [id,setId]=useState(''); const [rows,setRows]=useState<Template[]>([]); const [loaded,setLoaded]=useState(false); const [query,setQuery]=useState('');
 const [name,setName]=useState(''); const [body,setBody]=useState(''); const [language,setLanguage]=useState('ro'); const [category,setCategory]=useState('UTILITY');
 const [busy,setBusy]=useState(false); const [notice,setNotice]=useState(''); const [error,setError]=useState(''); const request=useRef(0);
 async function load(connectionId:string){const attempt=++request.current;const result=await api('templates/'+connectionId);if(attempt===request.current){setRows(result.data||[]);setLoaded(true);}}
 async function act(fn:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Operația a eșuat.');}finally{setBusy(false);}}
 const filtered=rows.filter(t=>`${t.name} ${t.status} ${statuses[t.status]||''}`.toLocaleLowerCase('ro').includes(query.toLocaleLowerCase('ro')));
 return <section className="wa-templates-panel">
  <div className="wa-template-toolbar"><label>Cont WhatsApp<select value={id} disabled={busy} onChange={e=>{request.current++;const next=e.target.value;setId(next);setRows([]);setLoaded(false);if(next)void act(()=>load(next));}}><option value="">Alege numărul agenției</option>{connections.filter(c=>c.status==='connected').map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><Button variant="outline" disabled={!id||busy} onClick={()=>void act(()=>load(id))}><RefreshCw size={15} className={busy?'animate-spin':''}/>Actualizează</Button></div>
  {error&&<p className="wa-alert" role="alert">{error}</p>}{notice&&<p className="wa-alert wa-success" role="status">{notice}</p>}
  <div className="wa-template-layout"><div className="wa-template-library"><div className="wa-section-heading"><h3>Biblioteca ta</h3><span className="wa-pill">{loaded?rows.length:'—'} șabloane</span></div><label className="wa-template-search"><Search size={16}/><input aria-label="Caută șabloane" placeholder="Caută după nume sau status…" value={query} onChange={e=>setQuery(e.target.value)}/></label>
   {!id?<div className="wa-template-empty"><FileText size={30}/><h3>Aici începe biblioteca ta.</h3><p>Selectează numărul pentru a vedea șabloanele din Meta.</p></div>:busy&&!loaded?<p className="wa-empty" role="status">Se încarcă șabloanele…</p>:loaded&&!filtered.length?<div className="wa-template-empty"><FileText size={28}/><h3>{rows.length?'Niciun rezultat':'Primul mesaj, pregătit de tine.'}</h3><p>{rows.length?'Încearcă un alt termen de căutare.':'Creează un șablon text pentru solicitările clienților sau ofertele agenției.'}</p></div>:filtered.map(t=><article className="wa-template-item" key={t.name+t.language}><span className="wa-icon"><FileText size={17}/></span><div><strong>{t.name}</strong><p>{t.language==='ro'?'Română':t.language} · {t.category==='UTILITY'?'Utilitar':t.category==='MARKETING'?'Marketing':t.category}</p></div><span className={'wa-pill '+(t.status==='APPROVED'?'wa-connected':'')}>{statuses[t.status]||t.status}</span></article>)}
  </div>{allowed?<div className="wa-template-editor"><div className="wa-section-heading"><div><span className="wa-eyebrow">UN MESAJ CU SCOP</span><h3>Creează un șablon</h3></div><MessageCircle size={22}/></div><form onSubmit={e=>{e.preventDefault();void act(async()=>{const result=await api('templates/'+id,'POST',{name,language,category,body});setNotice('Șablon creat în Meta: '+(statuses[result.status]||result.status)+'. Poate fi trimis numai după aprobare.');setName('');setBody('');await load(id);});}}><fieldset disabled={busy||!id}><label>Nume intern<Input required placeholder="confirmare_solicitare" pattern="[a-z][a-z0-9_]{1,99}" maxLength={100} value={name} onChange={e=>setName(e.target.value)}/><small>Litere mici, cifre și underscore. Exemplu: confirmare_vizionare</small></label><div className="wa-form-pair"><label>Limba<select value={language} onChange={e=>setLanguage(e.target.value)}><option value="ro">Română</option><option value="en_US">English (US)</option></select></label><label>Categorie<select value={category} onChange={e=>setCategory(e.target.value)}><option value="UTILITY">Utilitar</option><option value="MARKETING">Marketing</option></select></label></div><p className="wa-field-help">{category==='UTILITY'?'Pentru o solicitare sau tranzacție existentă.':'Pentru oferte, promovare și recomandări comerciale.'}</p><label>Mesaj<textarea required maxLength={1024} placeholder="Scrie mesajul pe care îl vor primi clienții…" value={body} onChange={e=>setBody(e.target.value)}/></label><div className="wa-counter"><span>Text simplu, fără variabile sau atașamente</span><span>{body.length}/1024</span></div><div className="wa-message-preview"><span>PREVIZUALIZARE</span><div>{body||'Mesajul tău va apărea aici.'}<small>ImoDeus <Check size={12}/></small></div></div><Button type="submit" disabled={busy||!id}><Send size={15}/>Trimite șablonul spre aprobare</Button><p className="wa-field-help">Meta verifică șablonul înainte de utilizare. Crearea lui nu trimite mesaje clienților.</p></fieldset></form></div>:<div className="wa-guide"><h3>Șabloane pentru agenție</h3><p>Crearea șabloanelor este disponibilă administratorilor autorizați.</p></div>}</div>
 </section>;
}
