export type GuideStep = { place: string; title: string; actions: string[]; result: string; note?: string; branches?: { title: string; actions: string[] }[] };
export const steps: GuideStep[] = [
{place:'PREGĂTIRE',title:'Adună datele înainte să deschizi Meta',actions:[
'Deschide ImoDeus și autentifică-te în contul tău.',
'Selectează agenția pentru care conectezi WhatsApp.',
'Verifică împreună cu administratorul agenției că ai rol de administrator CRM; acest rol permite conectarea și configurarea.',
'Pregătește denumirea publică a agenției, denumirea legală, adresa firmei, site-ul și e-mailul de business.',
'Pregătește profilul Facebook cu care vei administra firma în Meta.',
'Ține la îndemână telefonul numărului agenției și un alt telefon cu WhatsApp pentru verificarea primei conversații.'
],result:'Ai datele firmei și acces la cele două telefoane. Configurarea se face de către administratorul agenției.',note:'Dacă nu ai profil Facebook, intră pe facebook.com → Creează un cont nou; completează datele reale și confirmă telefonul sau e-mailul înainte de a continua.'},
{place:'META · BUSINESS SUITE',title:'Intră în Meta și creează portofoliul agenției',actions:[
'Apasă „Meta Business Suite” din acest ghid; se deschide business.facebook.com într-o filă nouă.',
'Autentifică-te cu profilul Facebook care va administra agenția.',
'În stânga sus, apasă meniul derulant de sub „Acasă” / „Home”.',
'Dacă vezi portofoliul agenției în listă, apasă numele lui și continuă la pasul 3.',
'Dacă agenția nu are încă portofoliu, apasă „Creează un portofoliu de business” / „Create a business portfolio”.',
'În câmpul pentru numele portofoliului, scrie denumirea publică a agenției, fără caractere speciale.',
'Completează prenumele și numele tău în câmpurile personale.',
'În câmpul pentru e-mailul de business, introdu adresa la care agenția primește corespondența Meta.',
'Apasă „Creează” / „Create” sau „Create portfolio”.',
'Deschide e-mailul primit de la Meta și apasă linkul de confirmare a adresei de business.',
'Revino în Business Suite și selectează portofoliul nou din meniul de sub „Acasă”.'
],result:'Numele portofoliului selectat este numele agenției tale.',note:'Dacă firma are deja portofoliu, cere proprietarului acces la acesta. Nu crea un duplicat. Contul WhatsApp va fi creat sau selectat în fereastra de conectare, la pasul 6.'},
{place:'META · SETĂRI',title:'Verifică accesul la portofoliu și contul WhatsApp',actions:[
'În meniul din stânga al Business Suite, apasă „Setări” / „Settings” (pictograma rotiță).',
'Deschide „Persoane” / „People”; dacă vezi grupul „Utilizatori” / „Users”, extinde-l mai întâi.',
'Apasă rândul cu numele profilului tău.',
'Verifică dacă accesul la portofoliu este „Control deplin” / „Full control”.',
'Dacă lipsește controlul deplin, cere proprietarului să deschidă același rând și să folosească opțiunea de modificare a accesului pentru a ți-l acorda.',
'Deschide „Informații despre portofoliul de business” / „Business portfolio info” (în unele conturi „Business info”).',
'Verifică denumirea legală, adresa firmei, telefonul și site-ul; folosește „Editează” / „Edit” pentru câmpurile incorecte, apoi „Salvează” / „Save”.',
'Dacă firma are deja WhatsApp în Meta, deschide „Conturi” / „Accounts” → „Conturi WhatsApp” / „WhatsApp accounts”.',
'Apasă contul agenției și verifică în secțiunea persoanelor că profilul tău are drepturile necesare pentru acel cont.'
],result:'Profilul Facebook folosit la conectare are control deplin asupra portofoliului și acces la contul WhatsApp existent.',note:'Accesul Meta și rolul CRM sunt separate. Dacă nu vezi meniul sau nu poți modifica accesul, proprietarul portofoliului trebuie să facă această verificare pentru tine.'},
{place:'PREGĂTIRE · NUMĂRUL',title:'Alege cum vei folosi numărul agenției',actions:[
'Pentru un număr nou, rezervă un număr al agenției care poate primi SMS sau apel.',
'Verifică să nu fie deja înregistrat în WhatsApp personal, WhatsApp Business App ori la alt furnizor.',
'Pentru această variantă vei alege „Număr dedicat Cloud API” în CRM.',
'Pentru numărul folosit deja în WhatsApp Business App, deschide magazinul de aplicații pe telefonul principal.',
'Caută „WhatsApp Business” și apasă „Actualizează” dacă butonul este disponibil.',
'Păstrează aplicația instalată și telefonul principal la îndemână.',
'Pentru această variantă vei alege „Număr existent în WhatsApp Business App” în CRM.',
'Dacă numărul este în WhatsApp personal sau la alt furnizor, cere suportului instrucțiunile de transfer înainte de a-l modifica; poți începe între timp cu un număr dedicat diferit.'
],result:'Ai ales una dintre cele două variante. La pasul 7 deschizi numai instrucțiunile pentru varianta ta.',note:'Nu șterge contul existent pentru a forța conectarea. Eligibilitatea Business App este verificată de Meta; conectarea nu garantează importul istoricului în CRM.'},
{place:'CRM · MARKETING → WHATSAPP',title:'Deschide formularul și apoi fereastra Meta',actions:[
'În ImoDeus, deschide „Marketing” din meniul lateral.',
'Deschide pagina „WhatsApp”.',
'Apasă „Conectează număr” deasupra cardurilor sau butonul cu același nume din acest ghid.',
'În lista „Tip de conectare WhatsApp”, selectează varianta aleasă la pasul 4.',
'Numai pentru număr dedicat: apasă câmpul „PIN de securitate din 6 cifre” și introdu exact 6 cifre alese de tine.',
'Păstrează PIN-ul în siguranță; vei avea nevoie de el pentru securitatea numărului.',
'Apasă „Conectează WhatsApp”.',
'Așteaptă să apară butonul „Deschide fereastra Meta”.',
'Apasă „Deschide fereastra Meta”.',
'Dacă browserul blochează fereastra, apasă pictograma de blocare a pop-up-urilor din bara de adrese, permite ferestrele pentru ImoDeus, apoi apasă din nou „Deschide fereastra Meta”.'
],result:'Fereastra Meta este deschisă, iar pagina ImoDeus rămâne deschisă în spate.',note:'PIN-ul ales în CRM nu este codul pe care îl primești prin SMS sau apel. Dacă butonul este dezactivat, citește mesajul din formular și contactează administratorul sau suportul ImoDeus.'},
{place:'META · FEREASTRA DE CONECTARE',title:'Selectează agenția și completează profilul WhatsApp',actions:[
'În fereastra Meta, autentifică-te cu profilul Facebook verificat la pasul 3.',
'Dacă apare „Continuă ca…” / „Continue as…”, verifică numele profilului și apasă butonul.',
'Pe ecranul de autorizare, citește accesul solicitat pentru conectarea WhatsApp și apasă butonul de continuare afișat.',
'Dacă următorul ecran este „Add your WhatsApp phone number”, urmează mai întâi verificarea numărului de la pasul 7, apoi revino la instrucțiunile pentru active de mai jos.',
'Pe „Select the business assets…” (selectarea activelor), deschide lista „Business portfolio”.',
'Selectează portofoliul agenției creat la pasul 2.',
'Deschide lista „WhatsApp Business account”.',
'Selectează contul WhatsApp al agenției; dacă nu există, selectează „Create a WhatsApp Business account”.',
'Apasă „Next” / „Înainte”.',
'Dacă apare „Enter business information for new assets”, scrie denumirea publică a agenției în „Name”.',
'În „Email”, introdu e-mailul de business al agenției.',
'În „Category”, selectează categoria care descrie agenția imobiliară.',
'În „Country”, selectează „Romania” / „România”, dacă firma este în România.',
'În „Website”, introdu adresa completă a site-ului agenției.',
'În „Time zone”, selectează fusul pentru București / Europe/Bucharest, dacă agenția lucrează în România.',
'Apasă „Next”.',
'Pentru Business App, dacă apare întâi profilul existent, verifică numele, numărul, categoria și site-ul, apoi apasă „Next”; selectează portofoliul în ecranul următor.',
'Dacă Business App cere crearea portofoliului în această fereastră, completează „Name”, „Email”, „Country” și „Website”, apoi apasă „Next”.'
],result:'Portofoliul și contul selectate aparțin agenției. Ai completat fiecare câmp obligatoriu înainte de „Next”.',note:'Meta introduce treptat o ordine nouă: numărul poate fi cerut înaintea activelor. Urmărește titlul ecranului: număr → pasul 7; portofoliu/profil → pasul 6. Nu crea o aplicație Meta for Developers și nu copia tokenuri în CRM.'},
{place:'META + TELEFON',title:'Verifică telefonul și încheie conectarea',actions:[
'Deschide mai jos instrucțiunile pentru varianta selectată în CRM și urmează-le în ordine.',
'Dacă după verificarea telefonului Meta cere portofoliul sau informațiile firmei, completează câmpurile de la pasul 6.',
'Pe ecranul de revizuire a permisiunilor, verifică numele portofoliului, contul WhatsApp și numărul afișat.',
'Păstrează accesul necesar gestionării contului WhatsApp și mesajelor pentru a permite funcționarea CRM-ului.',
'Apasă „Confirm” / „Confirmă” în dreapta jos.',
'Când Meta afișează confirmarea de succes, apasă „Finish” / „Finalizează”.',
'Revino în fila ImoDeus și așteaptă mesajul „Numărul a fost conectat”.'
],branches:[
{title:'Varianta A · Număr dedicat Cloud API',actions:[
'Pe „Add your WhatsApp phone number”, selectează adăugarea unui număr nou sau numărul existent al agenției, dacă este oferit și este cel pregătit.',
'Selectează țara și prefixul; pentru România, prefixul este +40.',
'Introdu numărul fără a repeta prefixul; de exemplu, pentru +40 759 319 033, introdu 759319033 după selectarea +40.',
'Dacă apare lista pentru profil, selectează crearea unui profil WhatsApp Business nou pentru numărul dedicat.',
'Apasă „Next”.',
'Pe ecranul de verificare, selectează „Text message” / „SMS” sau „Phone call” / „Apel”.',
'Verifică mesajul de sub „Verify your phone number”: Meta indică numărul către care a trimis codul; pentru un cod nou, folosește „Resend code” după intervalul de așteptare.',
'Deschide SMS-ul pe telefon sau răspunde la apel și notează codul primit.',
'Introdu cele 6 cifre primite în căsuțele „Verification code” din fereastra Meta.',
'Apasă „Next” în dreapta jos după completarea codului.'
]},
{title:'Varianta B · Număr existent în WhatsApp Business App',actions:[
'În fereastra Meta, introdu sau selectează numărul folosit în WhatsApp Business App, cu prefixul corect.',
'Apasă „Next” și verifică profilul agenției dacă Meta îl afișează.',
'Finalizează selectarea portofoliului conform pasului 6 dacă acest ecran apare acum.',
'Când Meta afișează un cod de acces sau un cod QR de conectare, lasă această fereastră deschisă pe calculator.',
'Pe telefonul principal, deschide WhatsApp Business.',
'Deschide mesajul de la contul oficial „Facebook Business”.',
'În mesaj, apasă „Connect” / „Conectează”.',
'Apasă „Connect to the Business Platform” / conectarea la platforma pentru firme.',
'Apasă „Confirm”.',
'Dacă apare alegerea pentru conversații, alege „Share chats” sau „Don’t share chats” conform deciziei agenției; această alegere nu garantează importul în ImoDeus.',
'Dacă telefonul cere „Enter Access code”, introdu codul afișat în fereastra Meta de pe calculator.',
'Dacă Meta afișează QR, apasă „Scan QR code instead” când este disponibil și scanează codul cu scannerul deschis în acest flux WhatsApp Business.',
'Dacă mesajul oficial nu apare, în WhatsApp Business deschide „Setări” / „Settings” → „Cont” / „Account” → „Business Platform” și urmează opțiunea de conectare indicată în ecranul Meta.',
'Așteaptă confirmarea în browser; dacă Meta cere „Time zone”, selectează fusul agenției și apasă „Next”.',
'Pe ecranul termenilor pentru Business App, citește condițiile și apasă „Confirm”.'
]}
],result:'Ai apăsat „Finish” în Meta și vezi numărul conectat în ImoDeus.',note:'Pentru Business App folosește mesajul oficial și fluxul Business Platform, nu meniul Dispozitive asociate / WhatsApp Web. Dacă Meta refuză eligibilitatea, folosește un număr dedicat diferit sau contactează suportul.'},
{place:'CRM · PRIVIRE DE ANSAMBLU',title:'Verifică toate stările din cardul numărului',actions:[
'În pagina WhatsApp, deschide fila „Privire de ansamblu”.',
'Apasă „Actualizează”.',
'Verifică denumirea agenției și numărul din card.',
'Verifică indicatorul „Conectat la Meta”.',
'Citește starea „Primire mesaje” și explicația de sub ea; aceasta poate necesita prima conversație de la pasul 13.',
'Citește separat starea și explicația pentru „Trimitere mesaje”.',
'Citește separat starea și explicația pentru „Șabloane”.',
'În subsolul cardului, verifică moneda contului.',
'Dacă moneda lipsește, configurează plata la pasul 10, apoi apasă „Conectează număr” și reautorizează același cont și număr.'
],result:'Numărul este corect și ai identificat explicația pentru orice stare care necesită configurare.',note:'„Actualizează” reîncarcă datele salvate în CRM. Moneda se recitește din Meta la conectare; nu apăsa „Deconectează” ca remediere de rutină.'},
{place:'META · WHATSAPP MANAGER',title:'Verifică numărul și eventualele solicitări Meta',actions:[
'Revino în fila Meta Business Suite.',
'În meniul de sub „Acasă”, selectează același portofoliu folosit la conectare.',
'Apasă „Toate instrumentele” / „All tools”.',
'Apasă „WhatsApp Manager”; alternativ, folosește butonul „WhatsApp Manager” din acest ghid.',
'Dacă Meta cere contul WhatsApp, selectează contul agenției.',
'Deschide „Numere de telefon” / „Phone numbers”.',
'Apasă rândul numărului conectat.',
'Verifică numărul, numele afișat și alertele; deschide fiecare alertă și citește acțiunea cerută.',
'Dacă Meta solicită verificarea firmei, revino în Business Suite → „Setări” → „Centrul de securitate” / „Security Centre”.',
'Apasă „Începe verificarea” / „Start verification” dacă opțiunea este disponibilă.',
'În câmpul pentru țară, selectează țara în care este înregistrată firma.',
'Completează separat denumirea legală, adresa, telefonul și site-ul firmei, exact ca în documentele ei; site-ul trebuie să se deschidă prin https://.',
'Apasă butonul de continuare din formular.',
'Dacă Meta oferă o firmă identificată, selecteaz-o numai dacă datele coincid; altfel alege opțiunea pentru firma care nu apare în listă.',
'Încarcă documentele solicitate în câmpurile dedicate, dacă Meta le cere.',
'Selectează o metodă oferită pentru confirmarea legăturii tale cu firma: e-mail, telefon, SMS sau WhatsApp.',
'Primește codul pe canalul ales și introdu-l în câmpul Meta. Dacă alegi verificarea domeniului, urmează în schimb pașii Meta pentru acel domeniu.'
,
'Apasă „Done” / „Gata” pentru trimiterea solicitării și verifică mesajul că aceasta a fost primită.'
],result:'Numărul apare în contul agenției și ai rezolvat sau ai trimis documentele pentru solicitările afișate de Meta.',note:'Verificarea firmei se pornește atunci când Meta o solicită sau o oferă pentru contul tău. Verificarea numărului, revizuirea numelui și abonamentul Meta Verified sunt procese separate.'},
{place:'META · FACTURARE ȘI PLĂȚI',title:'Adaugă cardul la contul de mesagerie WhatsApp',actions:[
'Revino în Meta Business Suite și selectează portofoliul agenției din meniul de sub „Acasă”.',
'Apasă „Setări” / „Settings” în meniul din stânga.',
'Apasă „Facturare și plăți” / „Billing & payments”.',
'Apasă „Conturi de mesagerie” / „Messaging accounts”.',
'Identifică în listă contul de mesagerie WhatsApp al agenției, asociat numărului conectat.',
'Pe rândul acelui cont, apasă „Adaugă o metodă de plată” / „Add payment method”. Dacă există deja o metodă, apasă „View details” / „Vezi detalii” pentru a o verifica.',
'Completează informațiile inițiale de plată cerute în formular și apasă „Next”.',
'În formularul cardului, introdu numărul cardului Visa sau Mastercard în câmpul corespunzător.',
'Completează data expirării, codul de securitate și numele titularului în câmpurile afișate.',
'Apasă „Save” / „Salvează” pentru card.',
'Finalizează autorizarea băncii dacă Meta o solicită.',
'În formularul cu informațiile firmei, completează denumirea, adresa de facturare și datele fiscale solicitate.',
'Apasă „Save” / „Salvează” pentru datele firmei.',
'Deschide fila „Settings” / „Setări” a contului de mesagerie și verifică să apară cardul adăugat.',
'În detaliile de facturare ale aceluiași cont, notează moneda pentru pasul 11 și verifică eventualele alerte de plată.'
],result:'Cardul este salvat pentru contul de mesagerie WhatsApp corect și cunoști moneda lui.',note:'Dacă vezi structura anterioară cu „WhatsApp Business accounts”, selectează contul agenției și deschide „Payment settings” pentru configurarea plății. Ai nevoie de drepturi de gestionare a plăților. Dacă facturarea este gestionată de un furnizor, cere suportului clarificarea înainte de a adăuga altă metodă. Plafonul CRM nu alimentează contul Meta.'},
{place:'CRM · CONSUM ȘI BUGET',title:'Salvează limita lunii curente',actions:[
'Revino în ImoDeus → Marketing → WhatsApp.',
'Apasă fila „Consum și buget” sau butonul cu același nume din ghid.',
'Apasă câmpul „Plafon lunar”.',
'Introdu suma maximă aprobată de agenție pentru luna curentă.',
'În lista „Monedă”, selectează moneda contului WhatsApp confirmată la pasul 10.',
'Apasă „Salvează plafonul”.',
'Așteaptă confirmarea „Plafonul lunii curente a fost salvat”.',
'Verifică suma și moneda din cardul de buget.',
'La începutul lunii următoare, revino în această filă și verifică plafonul pentru noua lună.'
],result:'Plafonul și moneda corectă apar în CRM.',note:'Selectorul oferă EUR, RON și USD. Pentru altă monedă, contactează suportul; nu selecta una diferită. Plafonul zero sau epuizat poate bloca mesajele cu cost. Sumele afișate sunt estimări.'},
{place:'CRM · ȘABLOANE',title:'Completează fiecare câmp al primului șablon',actions:[
'Apasă fila „Șabloane” în pagina WhatsApp.',
'În „Cont WhatsApp”, selectează numărul agenției.',
'Apasă „Actualizează” pentru a vedea șabloanele existente.',
'Dacă există un șablon potrivit cu starea „Aprobat”, îl poți folosi la pasul 14.',
'Pentru un șablon nou, mergi la formularul „Creează un șablon”.',
'În „Nume intern”, scrie confirmare_vizionare; folosește litere mici, cifre și underscore, fără spații sau diacritice.',
'În „Limba”, selectează „Română”.',
'În „Categorie”, alege „Utilitar” numai pentru confirmarea unei vizionări deja convenite; pentru oferte sau promovare, alege „Marketing”.',
'În „Mesaj”, pentru o vizionare convenită, scrie: „Bună! Îți confirmăm vizionarea stabilită cu agenția noastră. Dacă ai nevoie de ajutor, răspunde aici.”',
'Pentru acest prim șablon, folosește text simplu fără variabile sau atașamente; lasă butoanele opționale necompletate.',
'Citește previzualizarea mesajului.',
'Apasă „Trimite șablonul spre aprobare”.',
'Revino în fila „Șabloane” și apasă „Actualizează” pentru a vedea rezultatul revizuirii.',
'Continuă la trimitere numai când șablonul are starea „Aprobat”.'
],result:'Ai un șablon aprobat în contul numărului agenției.',note:'„În verificare”, „Respins”, „În pauză” și „Dezactivat” nu permit trimiterea. Pentru respingere: Meta → WhatsApp Manager → Message templates / Șabloane de mesaje → selectează șablonul → citește motivul; corectează textul sau creează unul nou. Meta poate schimba categoria.'},
{place:'TELEFON + CRM · INBOX',title:'Primește primul mesaj și răspunde din CRM',actions:[
'Pe al doilea telefon, deschide WhatsApp.',
'Pornește o conversație către numărul agenției, salvat cu prefix internațional.',
'Trimite mesajul „Bună! Aș dori informații despre o vizionare”.',
'În ImoDeus, apasă „Deschide Inbox” din pagina WhatsApp.',
'În lista conversațiilor, apasă conversația numărului de pe care ai trimis mesajul.',
'Dacă lucrezi ca agent și nu vezi conversația, cere administratorului să ți-o atribuie sau să îți acorde acces.',
'În zona de compunere, selectează „Răspuns către client”.',
'În lista „Șablon WhatsApp”, selectează „Mesaj liber”.',
'Scrie răspunsul către persoana de pe al doilea telefon.',
'Apasă „Verifică trimiterea”.',
'Citește rezultatul verificării și eventualele explicații; remediază orice blocaj afișat.',
'Dacă verificarea permite trimiterea, apasă butonul cu săgeata de trimitere din zona mesajului.',
'Pe al doilea telefon, verifică dacă răspunsul a fost primit.',
'Revino în Marketing → WhatsApp → „Privire de ansamblu” și apasă „Actualizează”.',
'Verifică dacă „Primire mesaje” este „Activ” după procesarea mesajului.'
],result:'Mesajul primit apare în Inbox, iar răspunsul ajunge la destinatar.',note:'Răspunsul liber este disponibil în intervalul de 24 de ore de la ultimul mesaj primit de la client. După acest interval folosește un șablon aprobat. „Trimis către Meta” nu confirmă singur livrarea.'},
{place:'CRM · INBOX → DETALII CLIENT',title:'Înregistrează acordul și trimite șablonul aprobat',actions:[
'Obține acordul real al persoanei pentru mesajele agenției și scopul lor.',
'Ca administrator CRM, deschide pe calculator conversația acelei persoane în Inbox.',
'Apasă „Detalii client”.',
'Extinde secțiunea „Consimțământ WhatsApp”.',
'În lista scopurilor, selectează „Comunicare de serviciu” pentru șablonul utilitar sau „Oferte / marketing” pentru cel de marketing.',
'În „Dovada și data acordului sau retragerii”, scrie data, canalul și scopul acordului; introdu minimum 10 caractere.',
'Apasă „Înregistrează”.',
'Revino în zona de compunere și selectează „Răspuns către client”.',
'Deschide lista „Șablon WhatsApp” și selectează șablonul cu starea „Aprobat”.',
'Pentru șablonul text simplu creat la pasul 12, lasă câmpul „Parametri șablon” gol.',
'Apasă „Verifică trimiterea”.',
'Verifică textul rezultat, costul estimat și explicațiile verificării.',
'Dacă trimiterea este permisă, apasă săgeata de trimitere.',
'Confirmă pe telefonul destinatarului că mesajul a fost primit.',
'Dacă persoana retrage acordul, revino în „Consimțământ WhatsApp”, selectează scopul sau „Oprește toate mesajele”, completează dovada retragerii și apasă „Retrage”.'
],result:'Acordul este înregistrat pentru scopul potrivit și ai confirmat livrarea șablonului.',note:'Nu înregistra acordul în lipsa lui. Pentru a începe o conversație cu un contact CRM existent: Inbox → „+” (Conversație nouă) → „ID contact CRM” → „Numărul agenției” → „Deschide conversația”; apoi selectează șablonul aprobat. Deschiderea conversației nu trimite un mesaj.'}
];
export const problems = [
['Nu pot apăsa Conectează WhatsApp','Verifică rolul de administrator CRM și mesajul de sub buton. Dacă accesul tot nu este disponibil, contactează suportul ImoDeus cu numele agenției și mesajul afișat.'],
['Fereastra Meta nu se deschide','Permite pop-up-urile pentru ImoDeus și apasă explicit „Deschide fereastra Meta”. Pentru o sesiune expirată, apasă „Anulează conectarea” și reia pasul 5.'],
['Nu văd portofoliul sau contul WhatsApp','În Meta verifică profilul conectat, apoi Setări → Persoane și Conturi → Conturi WhatsApp, conform pasului 3. Cere proprietarului acces la contul existent.'],
['Nu primesc codul SMS sau apelul','Verifică prefixul și numărul din ecranul Meta. Așteaptă intervalul afișat înainte de a cere alt cod. Folosește metoda alternativă oferită de Meta dacă prima nu funcționează.'],
['Nu primesc mesajul Facebook Business','Pe telefonul principal verifică actualizarea WhatsApp Business. Deschide Settings → Account → Business Platform și urmează ecranul de conectare Meta. Dacă numărul este neeligibil, folosește un număr dedicat diferit.'],
['Lipsește moneda sau apare Reconectare necesară','Pentru monedă, configurează plata de la pasul 10, apoi reautorizează același cont și număr prin „Conectează număr”. Pentru autorizare expirată, reia conectarea cu profilul Meta care are acces.'],
['Mesajul nu apare în Inbox','Verifică numărul către care ai trimis și accesul la conversație. Cere administratorului să verifice Inbox. Dacă mesajul lipsește și pentru el, trimite suportului numărul, ora și eroarea din card, fără PIN sau coduri de verificare.'],
['Verificarea trimiterii afișează o eroare','Acord lipsă → pasul 14; șablon neaprobat → pasul 12; interval de răspuns expirat → șablon aprobat; plafon → pasul 11; plată → pasul 10. Pentru tarif indisponibil sau altă restricție, trimite suportului explicația afișată.']
];
